== GSAK integrasjon

=== Kobling mellom Oppgave i GSAK og Behandling i Vedtaksløsning
Når VL under Behandling oppretter et Aksjonspunkt, skal dette håndteres manuelt at saksbehandler, og må derfor varsles til GSAK. VL kobler en Behandling til en OppgaveÅrsak gjennom OppgaveBehandlingKobling, og som sendes til GSAK. Eksempler på OppgaveÅrsak er Behandle sak, Registrerere søknad.

Det opprettes maksimum ett innslag av hver type OppgaveÅrsak. GSAK får ikke nye oppgaver hvis samme oppgave forsøkes opprettes flere ganger. Oppgaver skal avsluttes når VL er ferdig med behandlingen (Iverksette vedtak).

.Knytningen mellom GSAKs Oppgave og VLs Behandling skjer på følgende måte:
* VL angir referanse til Fagsak.id og OppgaveType.kode ved opprettelse.
* GSAK returnerer Oppgave. OppgaveId som lagres på VLs OppgaveBehandlingKobling.oppgave_id.
Hyperlink mellom GSAK og Vedtaksløsningen
Etter at oppgaven er opprettet i GSAK, vil saksbehandler kunne åpne Fagsak/Behandling gjennom link i GSAK (eller rettere sagt GoSys, som er GSAK sitt grafiske grensesnitt).

.Linken fra GSAK refererer til følgende URL i VL:
[source,xml]
----
<context_path>/oppgaveredirect?oppgaveId=<oppgaveId>&sakId=<sakId>
----

* context_path: iht. konfigurasjon for rotsti til VL
* oppgaveId: Refererer til GSAK sin oppgaveId, lagret lokalt på OppgaveBehandlingKobling.oppgave_id.
