
= Monitorering

== Logging

=== Retningslinjer for Logging
Applikasjonen logger hendelser utfra Auras retningslinjer i https://confluence.adeo.no/display/AURA/Logging[Logging] og https://confluence.adeo.no/display/AURA/Logback[Logback].

Applikasjonen skriver foreløpig kun til disse log-typene:

|===
|Loggtype|Beskrivelse|Loggdestinasjon

|Driftslogging/error-logg
|Tekniske problemer som må løses av drift. Dette er konfigurert til å være loggnivå ERROR fra applikasjonsloggen.
|/var/log/apps/<appnavn>_error.log

|Applikasjonslogging
|Mer detaljert informasjon om det som skjer i applikasjonen. Den som leser denne har sannsynligvis erfaring fra design og implementasjon av applikasjonen, og innholdet skal hjelpe til med problemsøking.

|/var/log/apps/<appnavn>.log
|Sporbarhetslogging|Følgende logges i sporingsloggen:
Manglende tilgang. Når en bruker forsøker å gjøre en operasjon, men mangler tilgang. Det logges da at tilgang ikke ble gitt (deny), brukerident for brukeren, hvilken operasjon som ble utført, og hvilke attributter som ble sendt til PDP.

Lesing av data. Det logges brukerident for brukeren, hvilken leseoperasjon som er kalt, en rekke metadata som beskriver hva som ble lest (for eksempel fødselsnumre, saksnummer)

Utføring av skriveoperasjon. Det logges brukerident for brukeren, hvilken skriveoperasjon som er kalt, en rekke metadata som beskriver hva som ble modifisert (for eksempel fødselsnumre, saksnummer, behandlingId, aksjonspunktId)

|/var/log/apps/<appnavn>_sporing.log

|Sikkerhetslogg |

Sikkerhetsrelatert informasjon: pålogging av bruker, endring av tilgang, forsøk å få tilgang etc
|/var/log/apps/<appnavn>_sikkerhet.log

|Serverlogger|Systemlogger for applikasjonstjeneren (SystemOut, SystemErr, GC-logger ol.)
|/var/log/apps/<appnavn>/server/

|===

=== Logging på INFO nivå
Informasjon som logges her på INFO nivå skal kun inneholde nøkler som ikke er personopplysninger.

Informasjon om tilstandstransisjoner (eks. behandlingssteg) eller tjeneste kall skal logges i definerte Choke points i applikasjonen og ikke spres utover forretningskoden.

*Følgende nøkler er whitelistet*

* BehandlingsId
* FagsakId
* Saksnummer (GSAK)
* Oppgave id (GSAK)
* JournalpostId
* PDP resultat
* Prosess task kode og id
* Behandlingssteg
* Kodeverk, eks:
- behandlingssteg
- aksjonspunkt
- vurderingspunkt
- etc
* Nøkler brukt i utveksling mot andre systemer for korrelering som ikke er knyttet direkte til person: eks. mot Oppdrag system, Dokprod

*Følgende er eksempler personopplysninger som ikke skal logges her*

* Meldinger
* Aktør id
* Fødselsnummer
* Navn
* Adresse
* Barn
* Søknad
* Foreldre

=== Logging på WARN nivå
Logging på WARN nivå dekker situasjoner der en feil oppstår, men systemet fortsatt vil fungere. Gjelder også feil på meldinger eller forbigående feil som påvirker enkeltsaker, eller tilgang til grensesnitt som er midlertid utilgjengelig (inklusiv transiente feil mot databasen)

I tillegg til underliggende feilmelding (cause) bør kontekst informasjon som f.eks nøkkelverdier (ref: Applikasjonslogg) eller lignende logges.

=== Logging på ERROR nivå
Logging på ERROR nivå dekker kritiske feil som oppstår i systemet, som er fatale for videre framdrift. Det kan være konfigurasjonsfeil, fatale databasefeil, eller feil i format på meldinger mottatt eller grensesnitt.

I tillegg til underliggende feilmelding (cause) bør kontekst informasjon som f.eks nøkkelverdier (ref: Applikasjonslogg) eller lignende logges.

Som en syretest på om noe bør logges som ERROR (istdf WARN), sett deg i mottakerens ståsted og vurder om det er en feil det er verdt å vekke noen om natten for, eller om det kan vente til neste forretningsdag.

=== Sporbarhetslogging
Logging til sporingsloggen gjøres automatisk av løsningen for endepunkter som har tilgangskontoroll, og automatikken dekker de fleste behov rundt dette (Se BeskyttetRessursInterceptor.java).

.Normalt kommer sporingslogg ved å legge på tilgangskontroll slik
[source,java]
----
@BeskyttetRessurs(aactionType = ActionType.READ, resourceType = ResourceType.FAGSAK, sporingslogg = true)
public List<FagsakDto> søkFagsaker(/*...*/)
/*...*/
----

I tilfellene det er behov for å logge mer enn hva som kommer fra tilgangskontroll-attributtene, må endepunktet logge direkte:
.Eksempel på ekstra-logging fra et endepunkt
[source,java]
----
String actionType = "read";
String endepunkt = "/api/eksempel/fagsak";
Sporingsdata sporingsdata = Sporingsdata.opprett().leggTilId(SporingsloggId.FAGSAK_ID, aktørId);
SporingsloggHelper.logSporing(ProsessTaskRestTjeneste.class, sporingsdata, actionType, endepunkt);
----

I tilfellene det er behov for å logge mer enn hva som kommer fra tilgangskontroll-attributtene, må endepunktet logge direkte:

.Unnta operasjon fra sporingslogg slik
[source,java]
----
@BeskyttetRessurs(actionType = ActionType.READ, resourceType = ResourceType.APPLIKASJON, sporingslogg = false)
public Map<String, Object> hentGruppertKodeliste()
/*...*/
----
Sporingsloggen skal være beskyttet, da den inneholder fødselsnumre.

=== Kontekst informasjon for logging
Applikasjonen setter MDC verdier for bruker-id og call-id ved inngangen til alle HTTP requests, samt kjøring av Tasks og mottak av meldinger.

Disse verdiene skrives i alle log-innslag.

=== Teknisk
Logging håndteres gjennom logback-rammeverket, som implementer slf4j sitt standard-api. Rammeverket konfigureres gjennom logback.xml som må ligge på classpath. For deployering mot Jboss er dette lagt inn i modul build-config. Loggingen kan overvåkes av sentral ELK-stakk som vist i ELK - miljøversikt

For lokal testkjøring brukes en egen logback.fil, logback-test.xml.

== Overvåkning
Vedtaksløsningen eksponerer interne REST-ressurser for overvåkning. Disse er:

=== Selftest
Begrenset til å støtte k8s isAlive / isReady / preStop

Hovedsaklig begrenset til om databaser er tilgjengelig.

=== Metrikker
Tilby endepunkt for prometheus

