= Automatiserte tasks (ProsessTask)

include::automasjon.adoc[leveloffset=+1]


Automatiske oppgaver som kjøres i bakgrunnen asynkront etter behov.
Tolererer feil og re-kjøres automatisk etter angitt feilhåndteringsstrategi.


== batch

=== Kjører angitt batch
====
* *Kode:* batch.runner
====

++++
Kjører batch som angitt i parametere
++++


=== Oppretter batchrunners og ny instans
====
* *Kode:* batch.scheduler
====

++++
 Enkel scheduler for dagens situasjon der man kjører batcher mandag-fredag og det er noe variasjon i parametere.

 Kan evt endres slik at BatchSchedulerTask kjører tidlig på døgnet og oppretter dagens batches (hvis ikke tidspunkt passert)

 Skal man utvide med ukentlige, måndedlige batcher etc bør man se på cron-aktige uttrykk for spesifikasjon av kjøring.
 FC har implementert et rammeverk på github

++++

== behandlingskontroll

=== Henlegg åpne behandlinger avslutt fagsak
====
* *Kode:* behandlingskontroll.henleggBehandling
====

++++
Henlegg behandlinger og avslutte sak, evt med flytting til Infotrygd.
++++


=== Gjenoppta behandling
====
* *Kode:* behandlingskontroll.gjenopptaBehandling
====

++++
 Utfører automatisk gjenopptagelse av en behandling som har
 et åpent aksjonspunkt som er et autopunkt og har en frist som er passert.

++++


=== Avslutt fagsak
====
* *Kode:* behandlingskontroll.fagsakAvslutning
====

++++
Avslutt fagsak hvis den er løpende og perioden for ytelsesvedtaket er passert
++++


=== Forsetter automatisk behandling.
====
* *Kode:* behandlingskontroll.fortsettBehandling
====

++++
 Kjører behandlingskontroll automatisk fra der prosessen står. Task som melder om kjører automatisk behandling for behandlingskontroll.  Starter i det steget behandlingen står og forsetter til den stopper på et Aksjonspunkt.
++++


=== Start behandling
====
* *Kode:* behandlingskontroll.startBehandling
====

++++
 Kjører behandlingskontroll automatisk fra start.
++++

=== Gjenoppta, oppdater, prosesser behandling
====
* *Kode:* behandlingskontroll.gjenopptaOppdaterBehandling
====

++++
 Utfører automatisk gjenopptagelse av en behandling som har
 et åpent aksjonspunkt som er et autopunkt og har en frist som er passert.

 Felles metode for hendelsesstyrt gjenopptak.
++++


=== Oppdater registerdata for behandling
====
* *Kode:* behandlingskontroll.registerdataOppdaterBehandling
====

++++
Oppdaterer registeredata for en åpen behandling
++++


=== Åpne behandling for endringer
====
* *Kode:* behandlingskontroll.åpneBehandlingForEndringer
====

++++
Åpner behandlingen for endringer ved å reaktivere inaktive aksjonspunkter før startpunktet og hopper til første startpunkt
++++


== behandlingsprosess

=== Automatisk etterkontroll
====
* *Kode:* behandlingsprosess.etterkontroll
====

++++
 @Dependent scope for å hente konfig ved hver kjøring.

++++


== behandlingsstotte

=== Automatisk sending av forlengelsesbrev
====
* *Kode:* behandlingsstotte.sendForlengelsesbrev
====


== dokumentbestiller

=== Bestill dokument
====
* *Kode:* dokumentbestiller.bestillDokument
====

++++
Produserer nytt dokument og sender det til dokumentproduksjonsstjenesten.
++++


== hendelser

=== Klargjøring av mottatt forretningshendelse.
====
* *Kode:* hendelser.klargjoering
====

++++
Første steg av håndtering av mottatt forretningshendelse. Identifiserer saker som er kandidat for revurdering.
++++


=== Fagsak knyttet til mottatt forretningshendelse.
====
* *Kode:* hendelser.håndterHendelsePåFagsak
====

++++
Identifisert fagsak fra håndtering av mottatt forretningshendelse håndteres videre som egen task. Splitt mellom identifisering av fagsak og videre eksekvering er for å sikre at samtidige prosesstasker på fagsak unngås.
++++


== innhentsaksopplysninger

=== Håndter mottatt dokument
====
* *Kode:* innhentsaksopplysninger.håndterMottattDokument
====

++++
Task som håndterer mottatte dokumenter ved å innhente saksopplysninger
++++


== iverksetteVedtak

=== Oppdater vedtak xml til Datavarehus
====
* *Kode:* iverksetteVedtak.regenererVedtakXmlTilDatavarehus
====

++++
Regenerer vedtaksxml til Datavarehus
++++


=== Vedtak til Datavarehus
====
* *Kode:* iverksetteVedtak.vedtakTilDatavarehus
====

++++
Produser og lever vedtaksxml til Datavarehus
++++


=== Avslutte behandling i modul Iverksette vedtak
====
* *Kode:* iverksetteVedtak.avsluttBehandling
====

++++
Avslutter behandlingen når brev er sendt og økonomioppdrag overført
++++


=== Kall til "Sende vedtaksbrev" i Iverksette vedtak
====
* *Kode:* iverksetteVedtak.sendVedtaksbrev
====

++++
Sender vedtaksbrev til brukeren via DokumentBestilleren, venter på kvittering
++++


=== Send oppdrag til Økonomi
====
* *Kode:* iverksetteVedtak.sendØkonomiOppdrag
====

++++
Hvis oppdrag ble lagret, send oppdrag til Økonomi
++++


=== Sett utbetaling på vent hvis privat arbeidsgiver
====
* *Kode:* iverksetteVedtak.oppgaveUtbetalingPåVent
====


=== Vurder neste oppgave i behandlingskøen.
====
* *Kode:* iverksetteVedtak.startBerørtBehandling
====

++++
Vurder neste oppgave i behandlingskøen.
++++


=== Kall til "Utbetale" i Iverksette vedtak
====
* *Kode:* iverksetteVedtak.oppdragTilØkonomi
====

++++
Dersom vedtaket medfører økonomioppdrag, lagrer dette oppdragsløsningen
++++


=== Vurder om arena ytelse skal opphøre
====
* *Kode:* iverksetteVedtak.oppgaveArena
====

++++
Vurder om oppgave skal opprettes for å opphøre arena ytelse
++++


== oppgavebehandling

=== Oppdater behandlende enhet for behandling
====
* *Kode:* oppgavebehandling.oppdaterEnhet
====

++++
Endring av behandlende enhet utenom ordinær logikk.
++++


=== Avslutter oppgave i GSAK
====
* *Kode:* oppgavebehandling.avsluttOppgave
====

++++
Task som avslutter oppgave i GSAK
++++


=== Oppretter oppgave i GSAK for sak sendt tilbake
====
* *Kode:* oppgavebehandling.opprettOppgaveSakSendtTilbake
====

++++
Oppretter oppgave i GSAK etter at beslutter sender saken tilbake til saksbehandler
++++


=== Oppretter oppgave i GSAK for å behandle sak
====
* *Kode:* oppgavebehandling.opprettOppgaveBehandleSak
====

++++
Oppretter oppgave i GSAK for å behandle sak
++++


=== Oppretter oppgave for godkjenning av vedtak i GSAK
====
* *Kode:* oppgavebehandling.opprettOppgaveGodkjennVedtak
====

++++
Task som oppretter oppgave for godkjenning av vedtak i GSAK
++++


=== Oppretter oppgave i GSAK for å registrere søknad
====
* *Kode:* oppgavebehandling.opprettOppgaveRegistrerSøknad
====

++++
Oppretter oppgave i GSAK for å registrere ustrukturert søknad
++++


=== Oppgave i GSAK for å ta over saken
====
* *Kode:* oppgavebehandling.opprettOppgaveSakTilInfotrygd
====

++++
Saker der skjæringstidspunkt inntreffer før 2019-01-01 må behandles av Infrotrygd da VL ikke besitter gamle bereningsregler.
++++


=== Oppretter oppgave i GSAK for å vurdere dokument
====
* *Kode:* oppgavebehandling.opprettOppgaveVurderDokument
====

++++
Oppretter oppgave i GSAK for å vurdere dokument
++++


=== Opprett oppgave vurder konsekvens for ytelse
====
* *Kode:* oppgavebehandling.opprettOppgaveVurderKonsekvens
====

++++
 ProsessTask som oppretter en oppgave i GSAK av typen vurder konsekvens for ytelse
++++

++++
Oppretter oppgave i GSAK for å vurdere konsekvens for ytelse
++++






