-- Baseline generated on 27.01.2020 16:02:23
-- INDEX

  CREATE INDEX "IDX_FAGSAK_RELASJON_1" ON "FAGSAK_RELASJON" ("FAGSAK_EN_ID")  ;

  CREATE INDEX "IDX_FAGSAK_RELASJON_2" ON "FAGSAK_RELASJON" ("FAGSAK_TO_ID")  ;

  CREATE INDEX "IDX_FAGSAK_RELASJON_3" ON "FAGSAK_RELASJON" ("KONTO_BEREGNING_ID")  ;

  CREATE INDEX "IDX_FAGSAK_RELASJON_4" ON "FAGSAK_RELASJON" ("OVERSTYRT_KONTO_BEREGNING_ID")  ;

  CREATE INDEX "IDX_FAGSAK_RELASJON_5" ON "FAGSAK_RELASJON" ("AVSLUTTNINGSDATO")  ;

  CREATE INDEX "IDX_BRUKER_6" ON "BRUKER" ("SPRAK_KODE")  ;

  CREATE INDEX "IDX_FAGSAK_1" ON "FAGSAK" ("FAGSAK_STATUS")  ;

  CREATE INDEX "IDX_FAGSAK_2" ON "FAGSAK" ("BRUKER_ROLLE")  ;

  CREATE INDEX "IDX_FAGSAK_3" ON "FAGSAK" ("BRUKER_ID")  ;

  CREATE INDEX "IDX_FAGSAK_7" ON "FAGSAK" ("YTELSE_TYPE")  ;

  CREATE INDEX "IDX_JOURNALPOST_1" ON "JOURNALPOST" ("FAGSAK_ID")  ;

  CREATE INDEX "IDX_BEHANDLING_6" ON "BEHANDLING" ("STARTPUNKT_TYPE")  ;

  CREATE INDEX "IDX_BEHANDLING_3" ON "BEHANDLING" ("BEHANDLING_TYPE")  ;

  CREATE INDEX "IDX_BEHANDLING_2" ON "BEHANDLING" ("BEHANDLING_STATUS")  ;

  CREATE INDEX "IDX_BEHANDLING_1" ON "BEHANDLING" ("FAGSAK_ID")  ;

  CREATE INDEX "IDX_OPPGAVE_BEHANDLING_KOBLI_6" ON "OPPGAVE_BEHANDLING_KOBLING" ("OPPGAVE_AARSAK")  ;

  CREATE INDEX "IDX_OPPGAVE_BEH_KOB_BEH_ID" ON "OPPGAVE_BEHANDLING_KOBLING" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_SOEKNAD_10" ON "SO_SOEKNAD" ("FAR_SOEKER_TYPE")  ;

  CREATE INDEX "IDX_SOEKNAD_11" ON "SO_SOEKNAD" ("BRUKER_ROLLE")  ;

  CREATE INDEX "IDX_SOEKNAD_12" ON "SO_SOEKNAD" ("SPRAK_KODE")  ;

  CREATE INDEX "IDX_TERMINBEKREFTELSE_1" ON "FH_TERMINBEKREFTELSE" ("FAMILIE_HENDELSE_ID")  ;

  CREATE INDEX "IDX_INNGANGSVILKAR_RES_1" ON "VILKAR_RESULTAT" ("VILKAR_RESULTAT")  ;

  CREATE INDEX "IDX_INNGANGSVILKAR_RES_2" ON "VILKAR_RESULTAT" ("ORIGINAL_BEHANDLING_ID")  ;

  CREATE INDEX "IDX_VILKAR_1" ON "VILKAR" ("VILKAR_UTFALL")  ;

  CREATE INDEX "IDX_VILKAR_2" ON "VILKAR" ("VILKAR_TYPE")  ;

  CREATE INDEX "IDX_VILKAR_3" ON "VILKAR" ("VILKAR_RESULTAT_ID")  ;

  CREATE INDEX "IDX_VILKAR_6" ON "VILKAR" ("AVSLAG_KODE")  ;

  CREATE INDEX "IDX_VILKAR_7" ON "VILKAR" ("VILKAR_UTFALL_MERKNAD")  ;

  CREATE INDEX "IDX_VILKAR_8" ON "VILKAR" ("VILKAR_UTFALL_MANUELL")  ;

  CREATE INDEX "IDX_VILKAR_9" ON "VILKAR" ("VILKAR_UTFALL_OVERSTYRT")  ;

  CREATE INDEX "IDX_BEREGNING_1" ON "BR_LEGACY_ES_BEREGNING" ("BEREGNING_RESULTAT_ID")  ;

  CREATE INDEX "IDX_SATS_1" ON "BR_SATS" ("SATS_TYPE")  ;

  CREATE INDEX "IDX_BEHANDLING_RESULTAT_1" ON "BEHANDLING_RESULTAT" ("INNGANGSVILKAR_RESULTAT_ID")  ;

  CREATE INDEX "IDX_BEHANDLING_RESULTAT_2" ON "BEHANDLING_RESULTAT" ("BEREGNING_RESULTAT_ID")  ;

  CREATE INDEX "IDX_BEHANDLING_RESULTAT_3" ON "BEHANDLING_RESULTAT" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_BEHANDLING_RESULTAT_4" ON "BEHANDLING_RESULTAT" ("BEHANDLING_RESULTAT_TYPE")  ;

  CREATE INDEX "IDX_BEHANDLING_RESULTAT_6" ON "BEHANDLING_RESULTAT" ("AVSLAG_ARSAK")  ;

  CREATE INDEX "IDX_AKSJONSPUNKT_9" ON "AKSJONSPUNKT" ("AKSJONSPUNKT_STATUS")  ;

  CREATE INDEX "IDX_AKSJONSPUNKT_8" ON "AKSJONSPUNKT" ("VENT_AARSAK")  ;

  CREATE INDEX "IDX_AKSJONSPUNKT_7" ON "AKSJONSPUNKT" ("AKSJONSPUNKT_DEF")  ;

  CREATE INDEX "IDX_AKSJONSPUNKT_6" ON "AKSJONSPUNKT" ("BEHANDLING_STEG_FUNNET")  ;

  CREATE INDEX "IDX_PROSESS_TASK_TYPE_1" ON "PROSESS_TASK_TYPE" ("FEILHANDTERING_ALGORITME")  ;

  CREATE INDEX "IDX_FH_ADOPSJON_6" ON "FH_ADOPSJON" ("OMSORG_VILKAAR_TYPE")  ;

  CREATE INDEX "IDX_ADOPSJON_1" ON "FH_ADOPSJON" ("FAMILIE_HENDELSE_ID")  ;

  CREATE INDEX "IDX_BEHANDLING_VEDTAK_6" ON "BEHANDLING_VEDTAK" ("IVERKSETTING_STATUS")  ;

  CREATE INDEX "IDX_VEDTAK_1" ON "BEHANDLING_VEDTAK" ("VEDTAK_RESULTAT_TYPE")  ;

  CREATE INDEX "IDX_VEDTAK_2" ON "BEHANDLING_VEDTAK" ("ANSVARLIG_SAKSBEHANDLER")  ;

  CREATE INDEX "IDX_VEDTAK_3" ON "BEHANDLING_VEDTAK" ("VEDTAK_DATO")  ;

  CREATE INDEX "IDX_HISTORIKKINNSLAG_01" ON "HISTORIKKINNSLAG" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_HISTORIKKINNSLAG_02" ON "HISTORIKKINNSLAG" ("BRUKER_KJOENN")  ;

  CREATE INDEX "IDX_HISTORIKKINNSLAG_03" ON "HISTORIKKINNSLAG" ("HISTORIKKINNSLAG_TYPE")  ;

  CREATE INDEX "IDX_HISTORIKKINNSLAG_6" ON "HISTORIKKINNSLAG" ("FAGSAK_ID")  ;

  CREATE INDEX "IDX_HISTORIKKINNSLAG_7" ON "HISTORIKKINNSLAG" ("HISTORIKK_AKTOER_ID")  ;

  CREATE INDEX "IDX_HISTINNSLAG_DOK_LINK_01" ON "HISTORIKKINNSLAG_DOK_LINK" ("HISTORIKKINNSLAG_ID")  ;

  CREATE INDEX "IDX_MOTTATTE_DOKUMENT_1" ON "MOTTATT_DOKUMENT" ("TYPE")  ;

  CREATE INDEX "IDX_MOTTATT_DOKUMENT_2" ON "MOTTATT_DOKUMENT" ("DOKUMENT_KATEGORI")  ;

  CREATE INDEX "IDX_MOTTATT_DOKUMENT_6" ON "MOTTATT_DOKUMENT" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_MOTTATT_DOKUMENT_7" ON "MOTTATT_DOKUMENT" ("FAGSAK_ID")  ;

  CREATE INDEX "IDX_MOTTATT_DOKUMENT_8" ON "MOTTATT_DOKUMENT" ("FORSENDELSE_ID")  ;

  CREATE INDEX "IDX_MOTTATT_DOKUMENT_9" ON "MOTTATT_DOKUMENT" ("JOURNALPOST_ID")  ;

  CREATE INDEX "IDX_VEDLEGG_1" ON "SOEKNAD_VEDLEGG" ("INNSENDINGSVALG")  ;

  CREATE INDEX "IDX_VEDLEGG_2" ON "SOEKNAD_VEDLEGG" ("SOEKNAD_ID")  ;

  CREATE INDEX "IDX_SOEKNAD_ANNEN_PART_1" ON "SO_ANNEN_PART" ("UTL_PERSON_IDENT_LAND")  ;

  CREATE INDEX "IDX_SOEKNAD_ANNEN_PART_2" ON "SO_ANNEN_PART" ("TYPE")  ;

  CREATE INDEX "IDX_SO_ANNEN_PART_3" ON "SO_ANNEN_PART" ("AKTOER_ID")  ;

  CREATE INDEX "IDX_SO_ANNEN_PART_4" ON "SO_ANNEN_PART" ("UTL_PERSON_IDENT")  ;

  CREATE INDEX "IDX_UTLANDSOPPHOLD_3" ON "MEDLEMSKAP_OPPG_LAND" ("LAND")  ;

  CREATE INDEX "IDX_MEDLEMSKAP_OPPG_LAND_6" ON "MEDLEMSKAP_OPPG_LAND" ("MEDLEMSKAP_OPPG_TILKNYT_ID")  ;

  CREATE INDEX "IDX_OPPDRAG_KONTROLL_1" ON "OPPDRAG_KONTROLL" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_OPPDRAG_KONTROLL_3" ON "OPPDRAG_KONTROLL" ("VENTER_KVITTERING")  ;

  CREATE INDEX "IDX_OPPDRAG_KONTROLL_4" ON "OPPDRAG_KONTROLL" ("PROSESS_TASK_ID")  ;

  CREATE INDEX "IDX_OKO_AVSTEMMING_115_1" ON "OKO_AVSTEMMING_115" ("KODE_KOMPONENT")  ;

  CREATE INDEX "IDX_OKO_AVSTEMMING_115_2" ON "OKO_AVSTEMMING_115" ("NOKKEL_AVSTEMMING")  ;

  CREATE INDEX "IDX_OKO_AVSTEMMING_115_3" ON "OKO_AVSTEMMING_115" ("TIDSPNKT_MELDING")  ;

  CREATE INDEX "IDX_OKO_OPPDRAG_110_1" ON "OKO_OPPDRAG_110" ("OPPDRAGS_KONTROLL_ID")  ;

  CREATE INDEX "IDX_OKO_OPPDRAG_110_3" ON "OKO_OPPDRAG_110" ("OPPDRAG_GJELDER_ID")  ;

  CREATE INDEX "IDX_OKO_OPPDRAG_110_6" ON "OKO_OPPDRAG_110" ("AVSTEMMING115_ID")  ;

  CREATE INDEX "IDX_OKO_OPPDRAG_ENHET_120_1" ON "OKO_OPPDRAG_ENHET_120" ("TYPE_ENHET")  ;

  CREATE INDEX "IDX_OKO_OPPDRAG_ENHET_120_2" ON "OKO_OPPDRAG_ENHET_120" ("ENHET")  ;

  CREATE INDEX "IDX_OKO_OPPDRAG_ENHET_120_3" ON "OKO_OPPDRAG_ENHET_120" ("OPPDRAG110_ID")  ;

  CREATE INDEX "IDX_OKO_OPPDRAG_LINJE_150_1" ON "OKO_OPPDRAG_LINJE_150" ("VEDTAK_ID")  ;

  CREATE INDEX "IDX_OKO_OPPDRAG_LINJE_150_3" ON "OKO_OPPDRAG_LINJE_150" ("SAKSBEH_ID")  ;

  CREATE INDEX "IDX_OKO_OPPDRAG_LINJE_150_4" ON "OKO_OPPDRAG_LINJE_150" ("UTBETALES_TIL_ID")  ;

  CREATE INDEX "IDX_OKO_OPPDRAG_LINJE_150_5" ON "OKO_OPPDRAG_LINJE_150" ("OPPDRAG110_ID")  ;

  CREATE INDEX "IDX_OKO_ATTESTANT_180_1" ON "OKO_ATTESTANT_180" ("ATTESTANT_ID")  ;

  CREATE INDEX "IDX_OKO_ATTESTANT_180_6" ON "OKO_ATTESTANT_180" ("OPPDRAGS_LINJE_150_ID")  ;

  CREATE INDEX "IDX_BEHANDLING_STEG_TILSTAND_1" ON "BEHANDLING_STEG_TILSTAND" ("BEHANDLING_STEG")  ;

  CREATE INDEX "IDX_BEHANDLING_STEG_TILSTAND_6" ON "BEHANDLING_STEG_TILSTAND" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_BEHANDLING_STEG_TILSTAND_7" ON "BEHANDLING_STEG_TILSTAND" ("BEHANDLING_STEG_STATUS")  ;

  CREATE INDEX "IDX_PROSESS_TASK_6" ON "PROSESS_TASK" ("BLOKKERT_AV")  ;

  CREATE INDEX "IDX_PROSESS_TASK_5" ON "PROSESS_TASK" ("TASK_GRUPPE")  ;

  CREATE INDEX "IDX_PROSESS_TASK_3" ON "PROSESS_TASK" ("NESTE_KJOERING_ETTER")  ;

  CREATE INDEX "IDX_PROSESS_TASK_2" ON "PROSESS_TASK" ("TASK_TYPE")  ;

  CREATE INDEX "IDX_PROSESS_TASK_1" ON "PROSESS_TASK" ("STATUS") ;

  CREATE INDEX "IDX_MEDLEMSKAP_PERIODER_03" ON "MEDLEMSKAP_PERIODER" ("MEDLEMSKAP_REGISTRERT_ID")  ;

  CREATE INDEX "IDX_MEDLEMSKAP_PERIODER_4" ON "MEDLEMSKAP_PERIODER" ("KILDE_TYPE")  ;

  CREATE INDEX "IDX_MEDLEMSKAP_PERIODER_3" ON "MEDLEMSKAP_PERIODER" ("DEKNING_TYPE")  ;

  CREATE INDEX "IDX_MEDLEMSKAP_PERIODER_2" ON "MEDLEMSKAP_PERIODER" ("MEDLEMSKAP_TYPE")  ;

  CREATE INDEX "IDX_MEDLEMSKAP_PERIODER_6" ON "MEDLEMSKAP_PERIODER" ("LOVVALG_LAND")  ;

  CREATE INDEX "IDX_MEDLEMSKAP_PERIODER_7" ON "MEDLEMSKAP_PERIODER" ("STUDIE_LAND")  ;

  CREATE INDEX "IDX_MEDLEMSKAP_VURDERING_6" ON "MEDLEMSKAP_VURDERING" ("MEDLEMSPERIODE_MANUELL_VURD")  ;

  CREATE INDEX "IDX_BEHANDLING_ARSAK_6" ON "BEHANDLING_ARSAK" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_BEHANDLING_ARSAK_7" ON "BEHANDLING_ARSAK" ("ORIGINAL_BEHANDLING_ID")  ;

  CREATE INDEX "IDX_KODELISTE_3" ON "KODELISTE" ("GYLDIG_FOM")  ;

  CREATE INDEX "IDX_KODELISTE_2" ON "KODELISTE" ("OFFISIELL_KODE")  ;

  CREATE INDEX "IDX_KODELISTE_1" ON "KODELISTE" ("KODE")  ;

  CREATE INDEX "IDX_KODELISTE_6" ON "KODELISTE" ("KODEVERK")  ;

  CREATE INDEX "IDX_VERGE_1" ON "VERGE" ("BRUKER_ID")  ;

  CREATE INDEX "IDX_VERGE_2" ON "VERGE" ("VERGE_TYPE")  ;

  CREATE INDEX "IDX_VERGE_ORGANISASJON" ON "VERGE" ("ORGANISASJON_ID")  ;

  CREATE INDEX "IDX_KLAGE_VURDERING_RESULTAT_1" ON "KLAGE_VURDERING_RESULTAT" ("KLAGE_RESULTAT_ID")  ;

  CREATE INDEX "IDX_KODELISTE_RELASJON_2" ON "KODELISTE_RELASJON" ("KODEVERK2", "KODE2")  ;

  CREATE INDEX "IDX_KODELISTE_RELASJON_1" ON "KODELISTE_RELASJON" ("KODEVERK1", "KODE1")  ;

  CREATE INDEX "IDX_KODELISTE_RELASJON_6" ON "KODELISTE_RELASJON" ("KODE1", "KODEVERK1")  ;

  CREATE INDEX "IDX_KODELISTE_RELASJON_7" ON "KODELISTE_RELASJON" ("KODE2", "KODEVERK2")  ;

  CREATE INDEX "IDX_GR_PERSONOPPLYSNING_01" ON "GR_PERSONOPPLYSNING" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_GR_PERSONOPPLYSNING_04" ON "GR_PERSONOPPLYSNING" ("OVERSTYRT_INFORMASJON_ID")  ;

  CREATE INDEX "IDX_GR_PERSONOPPLYSNING_6" ON "GR_PERSONOPPLYSNING" ("SO_ANNEN_PART_ID")  ;

  CREATE INDEX "IDX_GR_PERSONOPPLYSNING_03" ON "GR_PERSONOPPLYSNING" ("REGISTRERT_INFORMASJON_ID")  ;

  CREATE INDEX "IDX_GR_MEDLEMSKAP_04" ON "GR_MEDLEMSKAP" ("VURDERING_ID")  ;

  CREATE INDEX "IDX_GR_MEDLEMSKAP_03" ON "GR_MEDLEMSKAP" ("OPPGITT_ID")  ;

  CREATE INDEX "IDX_GR_MEDLEMSKAP_02" ON "GR_MEDLEMSKAP" ("REGISTRERT_ID")  ;

  CREATE INDEX "IDX_GR_MEDLEMSKAP_01" ON "GR_MEDLEMSKAP" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_FH_FAMILIE_HENDELSE_6" ON "FH_FAMILIE_HENDELSE" ("FAMILIE_HENDELSE_TYPE")  ;

  CREATE INDEX "IDX_FAMILIE_HENDELSE_1" ON "GR_FAMILIE_HENDELSE" ("SOEKNAD_FAMILIE_HENDELSE_ID")  ;

  CREATE INDEX "IDX_FAMILIE_HENDELSE_2" ON "GR_FAMILIE_HENDELSE" ("BEKREFTET_FAMILIE_HENDELSE_ID")  ;

  CREATE INDEX "IDX_FAMILIE_HENDELSE_3" ON "GR_FAMILIE_HENDELSE" ("OVERSTYRT_FAMILIE_HENDELSE_ID")  ;

  CREATE INDEX "IDX_GR_FAMILIE_HENDELSE_6" ON "GR_FAMILIE_HENDELSE" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_GR_VERGE_02" ON "GR_VERGE" ("VERGE_ID")  ;

  CREATE INDEX "IDX_GR_VERGE_01" ON "GR_VERGE" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_BEREGNINGSGRUNNLAG_02" ON "BEREGNINGSGRUNNLAG" ("SKJARINGSTIDSPUNKT")  ;

  CREATE INDEX "IDX_BG_PERIODE_01" ON "BEREGNINGSGRUNNLAG_PERIODE" ("BEREGNINGSGRUNNLAG_ID")  ;

  CREATE INDEX "IDX_BG_PERIODE_02" ON "BEREGNINGSGRUNNLAG_PERIODE" ("BG_PERIODE_FOM")  ;

  CREATE INDEX "IDX_BG_PERIODE_03" ON "BEREGNINGSGRUNNLAG_PERIODE" ("BG_PERIODE_TOM")  ;

  CREATE INDEX "IDX_BG_PR_STATUS_OG_ANDEL_01" ON "BG_PR_STATUS_OG_ANDEL" ("BG_PERIODE_ID")  ;

  CREATE INDEX "IDX_BG_PR_STATUS_OG_ANDEL_02" ON "BG_PR_STATUS_OG_ANDEL" ("AKTIVITET_STATUS")  ;

  CREATE INDEX "IDX_SAMMENLIGNINGSGRUNNLAG_01" ON "SAMMENLIGNINGSGRUNNLAG" ("BEREGNINGSGRUNNLAG_ID")  ;

  CREATE INDEX "IDX_SAMMENLIGNINGSGRUNNLAG_02" ON "SAMMENLIGNINGSGRUNNLAG" ("SAMMENLIGNINGSPERIODE_FOM")  ;

  CREATE INDEX "IDX_SAMMENLIGNINGSGRUNNLAG_03" ON "SAMMENLIGNINGSGRUNNLAG" ("SAMMENLIGNINGSPERIODE_TOM")  ;

  CREATE INDEX "IDX_SAMMENLIGNINGSGRUNNLAG_04" ON "SAMMENLIGNINGSGRUNNLAG" ("RAPPORTERT_PR_AAR")  ;

  CREATE INDEX "IDX_BG_AKTIVITET_STATUS_01" ON "BG_AKTIVITET_STATUS" ("BEREGNINGSGRUNNLAG_ID")  ;

  CREATE INDEX "IDX_BG_AKTIVITET_STATUS_02" ON "BG_AKTIVITET_STATUS" ("AKTIVITET_STATUS")  ;

  CREATE INDEX "IDX_BG_AKTIVITET_STATUS_03" ON "BG_AKTIVITET_STATUS" ("HJEMMEL")  ;

  CREATE INDEX "IDX_STOENADSKONTO_1" ON "STOENADSKONTO" ("STOENADSKONTOBEREGNING_ID")  ;

  CREATE INDEX "IDX_INNSYN_6" ON "INNSYN" ("INNSYN_RESULTAT_TYPE")  ;

  CREATE INDEX "IDX_GR_BEREGNINGSGRUNNLAG_02" ON "GR_BEREGNINGSGRUNNLAG" ("REGISTER_AKTIVITETER_ID")  ;

  CREATE INDEX "IDX_GR_BEREGNINGSGRUNNLAG_03" ON "GR_BEREGNINGSGRUNNLAG" ("SAKSBEHANDLET_AKTIVITETER_ID")  ;

  CREATE INDEX "IDX_GR_BEREGNINGSGRUNNLAG_04" ON "GR_BEREGNINGSGRUNNLAG" ("BA_OVERSTYRINGER_ID")  ;

  CREATE INDEX "IDX_GR_BEREGNINGSGRUNNLAG_05" ON "GR_BEREGNINGSGRUNNLAG" ("BR_OVERSTYRINGER_ID")  ;

  CREATE INDEX "IDX_GR_BEREGNINGSGRUNNLAG_6" ON "GR_BEREGNINGSGRUNNLAG" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_GR_BEREGNINGSGRUNNLAG_7" ON "GR_BEREGNINGSGRUNNLAG" ("BEREGNINGSGRUNNLAG_ID")  ;

  CREATE INDEX "IDX_YF_FORDELING_PERIODE_9" ON "YF_FORDELING_PERIODE" ("ARBEIDSGIVER_ORGNR")  ;

  CREATE INDEX "IDX_YF_FORDELING_PERIODE_7" ON "YF_FORDELING_PERIODE" ("FORDELING_PERIODE_KILDE")  ;

  CREATE INDEX "IDX_YF_FORDELING_PERIODE_6" ON "YF_FORDELING_PERIODE" ("VURDERING_TYPE")  ;

  CREATE INDEX "IDX_YF_FORDELING_PERIODE_4" ON "YF_FORDELING_PERIODE" ("FORDELING_ID")  ;

  CREATE INDEX "IDX_YF_FORDELING_PERIODE_3" ON "YF_FORDELING_PERIODE" ("AARSAK_TYPE")  ;

  CREATE INDEX "IDX_YF_FORDELING_PERIODE_2" ON "YF_FORDELING_PERIODE" ("PERIODE_TYPE")  ;

  CREATE INDEX "IDX_YF_FORDELING_PERIODE_1" ON "YF_FORDELING_PERIODE" ("MORS_AKTIVITET")  ;

  CREATE INDEX "IDX_GR_YTELSES_FORDELING_01" ON "GR_YTELSES_FORDELING" ("UTTAK_DOKUMENTASJON_ID")  ;

  CREATE INDEX "IDX_GR_YTELSES_FORDELING_02" ON "GR_YTELSES_FORDELING" ("UTENOMSORG_ID")  ;

  CREATE INDEX "IDX_GR_YTELSES_FORDELING_04" ON "GR_YTELSES_FORDELING" ("OVERSTYRT_FORDELING_ID")  ;

  CREATE INDEX "IDX_GR_YTELSES_FORDELING_06" ON "GR_YTELSES_FORDELING" ("ALENEOMSORG_ID")  ;

  CREATE INDEX "IDX_GR_YTELSES_FORDELING_07" ON "GR_YTELSES_FORDELING" ("SO_FORDELING_ID")  ;

  CREATE INDEX "IDX_GR_YTELSES_FORDELING_08" ON "GR_YTELSES_FORDELING" ("SO_DEKNINGSGRAD_ID")  ;

  CREATE INDEX "IDX_GR_YTELSES_FORDELING_09" ON "GR_YTELSES_FORDELING" ("SO_RETTIGHET_ID")  ;

  CREATE INDEX "IDX_GR_YTELSES_FORDELING_10" ON "GR_YTELSES_FORDELING" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_GR_YTELSES_FORDELING_11" ON "GR_YTELSES_FORDELING" ("YF_AVKLART_DATO_ID")  ;

  CREATE INDEX "IDX_GR_YTELSES_FORDELING_12" ON "GR_YTELSES_FORDELING" ("ANNEN_FORELDER_HAR_RETT_ID")  ;

  CREATE INDEX "IDX_GR_YTELSES_FORDELING_15" ON "GR_YTELSES_FORDELING" ("JUSTERT_FORDELING_ID")  ;

  CREATE INDEX "IDX_OPPTJENING_01" ON "OPPTJENING" ("VILKAR_RESULTAT_ID")  ;

  CREATE INDEX "IDX_OPPTJENING_AKTIVITET_01" ON "OPPTJENING_AKTIVITET" ("OPPTJENINGSPERIODE_ID")  ;

  CREATE INDEX "IDX_INNSYN_DOKUMENT_6" ON "INNSYN_DOKUMENT" ("INNSYN_ID")  ;

  CREATE INDEX "IDX_BR_PERIODE_01" ON "BR_PERIODE" ("BEREGNINGSRESULTAT_FP_ID")  ;

  CREATE INDEX "IDX_BR_PERIODE_02" ON "BR_PERIODE" ("BR_PERIODE_FOM")  ;

  CREATE INDEX "IDX_BR_PERIODE_03" ON "BR_PERIODE" ("BR_PERIODE_TOM")  ;

  CREATE INDEX "IDX_BEREGNINGSRESULTAT_ANDEL_7" ON "BR_ANDEL" ("ARBEIDSGIVER_ORGNR")  ;

  CREATE INDEX "IDX_BEREGNINGSRESULTAT_ANDEL_2" ON "BR_ANDEL" ("AKTIVITET_STATUS")  ;

  CREATE INDEX "IDX_BR_ANDEL_01" ON "BR_ANDEL" ("BR_PERIODE_ID")  ;

  CREATE INDEX "IDX_BEREGNINGSRES_ANDEL_11" ON "BR_ANDEL" ("ARBEIDSFORHOLD_INTERN_ID")  ;

  CREATE INDEX "IDX_RES_BEREGNINGSRESULTAT_F_6" ON "BR_RESULTAT_BEHANDLING" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_UTTAKSPERIODEGRENSE_1" ON "UTTAKSPERIODEGRENSE" ("BEHANDLING_RESULTAT_ID")  ;

  CREATE INDEX "IDX_HISTORIKKINNSLAG_DEL_1" ON "HISTORIKKINNSLAG_DEL" ("HISTORIKKINNSLAG_ID")  ;

  CREATE INDEX "IDX_HISTORIKKINNSLAG_FELT_1" ON "HISTORIKKINNSLAG_FELT" ("HISTORIKKINNSLAG_DEL_ID")  ;

  CREATE INDEX "IDX_HISTORIKKINNSLAG_FELT_3" ON "HISTORIKKINNSLAG_FELT" ("NAVN", "KL_NAVN")  ;

  CREATE INDEX "IDX_HISTORIKKINNSLAG_FELT_4" ON "HISTORIKKINNSLAG_FELT" ("TIL_VERDI_KODE", "KL_TIL_VERDI")  ;

  CREATE INDEX "IDX_HISTORIKKINNSLAG_FELT_5" ON "HISTORIKKINNSLAG_FELT" ("FRA_VERDI_KODE", "KL_FRA_VERDI")  ;

  CREATE INDEX "IDX_OKO_REFUSJONSINFO_156_6" ON "OKO_REFUSJONSINFO_156" ("OPPDRAGS_LINJE_150_ID")  ;

  CREATE INDEX "IDX_OKO_GRAD_170_6" ON "OKO_GRAD_170" ("OPPDRAGS_LINJE_150_ID")  ;

  CREATE INDEX "IDX_YF_DOK_PERIODER_1" ON "YF_DOKUMENTASJON_PERIODER" ("DOKUMENTASJON_KLASSE")  ;

  CREATE INDEX "IDX_YF_DOKUMENTASJON_PERIODE_1" ON "YF_DOKUMENTASJON_PERIODE" ("PERIODER_ID")  ;

  CREATE INDEX "IDX_YF_DOK_PERIODE_2" ON "YF_DOKUMENTASJON_PERIODE" ("DOKUMENTASJON_TYPE")  ;

  CREATE INDEX "IDX_YF_DOK_PERIODE_3" ON "YF_DOKUMENTASJON_PERIODE" ("DOKUMENTASJON_KLASSE")  ;

  CREATE INDEX "IDX_MEDLEMSKAP_VILKAR_PERIOD_6" ON "MEDLEMSKAP_VILKAR_PERIODER" ("MEDLEMSKAP_VILKAR_PERIODE_ID")  ;

  CREATE INDEX "IDX_MEDLEMSKAP_V_P_2" ON "MEDLEMSKAP_VILKAR_PERIODER" ("VILKAR_UTFALL_MERKNAD")  ;

  CREATE INDEX "IDX_M_V_P_1" ON "MEDLEMSKAP_VILKAR_PERIODE" ("OVERSTYRT_UTFALL")  ;

  CREATE INDEX "IDX_M_V_P_3" ON "MEDLEMSKAP_VILKAR_PERIODE" ("AVSLAGSARSAK")  ;

  CREATE INDEX "IDX_GR_MEDLEMSKAP_VILKAR_PER_6" ON "GR_MEDLEMSKAP_VILKAR_PERIODE" ("VILKAR_RESULTAT_ID")  ;

  CREATE INDEX "IDX_GR_MEDLEMSKAP_VILKAR_PER_7" ON "GR_MEDLEMSKAP_VILKAR_PERIODE" ("MEDLEMSKAP_VILKAR_PERIODE_ID")  ;

  CREATE INDEX "IDX_OPPDRAG_KVITTERING_1" ON "OPPDRAG_KVITTERING" ("OPPDRAG_110_ID")  ;

  CREATE INDEX "IDX_UTTAK_RESULTAT_PERIODE" ON "UTTAK_RESULTAT_PERIODE" ("UTTAK_RESULTAT_PERIODER_ID")  ;

  CREATE INDEX "IDX_UTTAK_RESULTAT_PERIODE_10" ON "UTTAK_RESULTAT_PERIODE" ("OPPHOLD_AARSAK")  ;

  CREATE INDEX "IDX_UTTAK_RESULTAT_PERIODE_11" ON "UTTAK_RESULTAT_PERIODE" ("OVERFOERING_AARSAK")  ;

  CREATE INDEX "IDX_UTTAK_RESULTAT_PERIODE_2" ON "UTTAK_RESULTAT_PERIODE" ("PERIODE_RESULTAT_AARSAK")  ;

  CREATE INDEX "IDX_UTTAK_RESULTAT_PERIODE_5" ON "UTTAK_RESULTAT_PERIODE" ("GRADERING_AVSLAG_AARSAK")  ;

  CREATE INDEX "IDX_UTTAK_RESULTAT_PERIODE_6" ON "UTTAK_RESULTAT_PERIODE" ("PERIODE_RESULTAT_TYPE")  ;

  CREATE INDEX "IDX_UTTAK_RESULTAT_PERIODE_9" ON "UTTAK_RESULTAT_PERIODE" ("PERIODE_SOKNAD_ID")  ;

  CREATE INDEX "IDX_UTTAK_RESULTAT_02" ON "UTTAK_RESULTAT" ("BEHANDLING_RESULTAT_ID")  ;

  CREATE INDEX "IDX_UTTAK_RESULTAT_03" ON "UTTAK_RESULTAT" ("OPPRINNELIG_PERIODER_ID")  ;

  CREATE INDEX "IDX_UTTAK_RESULTAT_04" ON "UTTAK_RESULTAT" ("OVERSTYRT_PERIODER_ID")  ;

  CREATE INDEX "IDX_FAGSAK_PROSESS_TASK_4" ON "FAGSAK_PROSESS_TASK" ("GRUPPE_SEKVENSNR")  ;

  CREATE INDEX "IDX_FAGSAK_PROSESS_TASK_3" ON "FAGSAK_PROSESS_TASK" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_FAGSAK_PROSESS_TASK_2" ON "FAGSAK_PROSESS_TASK" ("PROSESS_TASK_ID")  ;

  CREATE INDEX "IDX_FAGSAK_PROSESS_TASK_1" ON "FAGSAK_PROSESS_TASK" ("FAGSAK_ID")  ;

  CREATE INDEX "IDX_UTHENDELSE_AKTOER_ID" ON "UTGAAENDE_HENDELSE" ("AKTOER_ID")  ;

  CREATE INDEX "IDX_UTHENDELSE_KILDE_ID" ON "UTGAAENDE_HENDELSE" ("KILDE_ID")  ;

  CREATE INDEX "IDX_UTHENDELSE_SEKVENSNUMMER" ON "UTGAAENDE_HENDELSE" ("SEKVENSNUMMER")  ;

  CREATE INDEX "IDX_UTHENDELSE_TYPE" ON "UTGAAENDE_HENDELSE" ("TYPE")  ;

  CREATE INDEX "IDX_PO_ADRESSE_2" ON "PO_ADRESSE" ("PO_INFORMASJON_ID")  ;

  CREATE INDEX "IDX_PO_ADRESSE_3" ON "PO_ADRESSE" ("AKTOER_ID")  ;

  CREATE INDEX "IDX_PO_ADRESSE_5" ON "PO_ADRESSE" ("ADRESSE_TYPE")  ;

  CREATE INDEX "IDX_PO_RELASJON_1" ON "PO_RELASJON" ("PO_INFORMASJON_ID")  ;

  CREATE INDEX "IDX_PO_RELASJON_2" ON "PO_RELASJON" ("FRA_AKTOER_ID")  ;

  CREATE INDEX "IDX_PO_RELASJON_3" ON "PO_RELASJON" ("TIL_AKTOER_ID")  ;

  CREATE INDEX "IDX_PO_RELASJON_5" ON "PO_RELASJON" ("RELASJONSROLLE")  ;

  CREATE INDEX "IDX_PO_STATSBORGERSKAP_1" ON "PO_STATSBORGERSKAP" ("PO_INFORMASJON_ID")  ;

  CREATE INDEX "IDX_PO_STATSBORGERSKAP_2" ON "PO_STATSBORGERSKAP" ("AKTOER_ID")  ;

  CREATE INDEX "IDX_PO_STATSBORGERSKAP_4" ON "PO_STATSBORGERSKAP" ("STATSBORGERSKAP")  ;

  CREATE INDEX "IDX_PO_PERSONSTATUS_1" ON "PO_PERSONSTATUS" ("PO_INFORMASJON_ID")  ;

  CREATE INDEX "IDX_PO_PERSONSTATUS_2" ON "PO_PERSONSTATUS" ("AKTOER_ID")  ;

  CREATE INDEX "IDX_PO_PERSONSTATUS_4" ON "PO_PERSONSTATUS" ("PERSONSTATUS")  ;

  CREATE INDEX "IDX_PO_PERSONOPPLYSNING_1" ON "PO_PERSONOPPLYSNING" ("PO_INFORMASJON_ID")  ;

  CREATE INDEX "IDX_PO_PERSONOPPLYSNING_2" ON "PO_PERSONOPPLYSNING" ("AKTOER_ID")  ;

  CREATE INDEX "IDX_PO_PERSONOPPLYSNING_3" ON "PO_PERSONOPPLYSNING" ("REGION")  ;

  CREATE INDEX "IDX_PO_PERSONOPPLYSNING_4" ON "PO_PERSONOPPLYSNING" ("BRUKER_KJOENN")  ;

  CREATE INDEX "IDX_PO_PERSONOPPLYSNING_5" ON "PO_PERSONOPPLYSNING" ("SIVILSTAND_TYPE")  ;

  CREATE INDEX "IDX_UTTAK_AKTIVITET_4" ON "UTTAK_AKTIVITET" ("ARBEIDSGIVER_ORGNR")  ;

  CREATE INDEX "IDX_UTTAK_AKTIVITET_1" ON "UTTAK_AKTIVITET" ("UTTAK_ARBEID_TYPE")  ;

  CREATE INDEX "IDX_UTTAK_AKTIVITET_11" ON "UTTAK_AKTIVITET" ("ARBEIDSFORHOLD_INTERN_ID")  ;

  CREATE INDEX "IDX_UTTAK_RESULTAT_SOKNAD_2" ON "UTTAK_RESULTAT_PERIODE_SOKNAD" ("MORS_AKTIVITET")  ;

  CREATE INDEX "IDX_UTTAK_RES_PER_SOKNAD_1" ON "UTTAK_RESULTAT_PERIODE_SOKNAD" ("PERIODE_TYPE")  ;

  CREATE INDEX "IDX_UTTAK_RESULTAT_DOK_REGEL_1" ON "UTTAK_RESULTAT_DOK_REGEL" ("MANUELL_BEHANDLING_AARSAK")  ;

  CREATE INDEX "IDX_UTTAK_RESULTAT_DOK_REGEL_2" ON "UTTAK_RESULTAT_DOK_REGEL" ("UTTAK_RESULTAT_PERIODE_ID")  ;

  CREATE INDEX "IDX_UTTAK_RES_PERIODE_AKT_1" ON "UTTAK_RESULTAT_PERIODE_AKT" ("UTTAK_RESULTAT_PERIODE_ID")  ;

  CREATE INDEX "IDX_UTTAK_RES_PERIODE_AKT_2" ON "UTTAK_RESULTAT_PERIODE_AKT" ("UTTAK_AKTIVITET_ID")  ;

  CREATE INDEX "IDX_UTTAK_RES_PERIODE_AKT_3" ON "UTTAK_RESULTAT_PERIODE_AKT" ("TREKKONTO")  ;

  CREATE INDEX "IDX_GR_SOEKNAD_2" ON "GR_SOEKNAD" ("SOEKNAD_ID")  ;

  CREATE INDEX "IDX_GR_SOEKNAD_1" ON "GR_SOEKNAD" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_BR_FERIEPENGER_1" ON "BR_FERIEPENGER" ("BEREGNINGSRESULTAT_FP_ID")  ;

  CREATE INDEX "IDX_BR_FERIEPENGER_PR_AAR_1" ON "BR_FERIEPENGER_PR_AAR" ("BR_FERIEPENGER_ID")  ;

  CREATE INDEX "IDX_BR_FERIEPENGER_PR_AAR_2" ON "BR_FERIEPENGER_PR_AAR" ("BEREGNINGSRESULTAT_ANDEL_ID")  ;

  CREATE INDEX "IDX_TORINN_RES_GR_06" ON "TOTRINNRESULTATGRUNNLAG" ("IAY_GRUNNLAG_UUID")  ;

  CREATE INDEX "IDX_TORINN_RES_GR_05" ON "TOTRINNRESULTATGRUNNLAG" ("BEREGNINGSGRUNNLAG_ID")  ;

  CREATE INDEX "IDX_TORINN_RES_GR_04" ON "TOTRINNRESULTATGRUNNLAG" ("UTTAK_RESULTAT_ID")  ;

  CREATE INDEX "IDX_TORINN_RES_GR_03" ON "TOTRINNRESULTATGRUNNLAG" ("YTELSES_FORDELING_GRUNNLAG_ID")  ;

  CREATE INDEX "IDX_TORINN_RES_GR_01" ON "TOTRINNRESULTATGRUNNLAG" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_BG_PERIODE_AARSAK_1" ON "BG_PERIODE_AARSAK" ("BG_PERIODE_ID")  ;

  CREATE INDEX "IDX_TOTRINNSVURDERING" ON "TOTRINNSVURDERING" ("AKSJONSPUNKT_DEF")  ;

  CREATE INDEX "IDX_TOTRINNSVURDERING_2" ON "TOTRINNSVURDERING" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_VURDER_AARSAK_2" ON "VURDER_AARSAK_TTVURDERING" ("AARSAK_TYPE")  ;

  CREATE INDEX "IDX_VURDER_AARSAK" ON "VURDER_AARSAK_TTVURDERING" ("TOTRINNSVURDERING_ID")  ;

  CREATE INDEX "IDX_KODELISTE_NAVN_I18N_1" ON "KODELISTE_NAVN_I18N" ("KL_KODEVERK", "KL_KODE")  ;

  CREATE INDEX "IDX_BG_FAKTA_BER_TILFELLE_1" ON "BG_FAKTA_BER_TILFELLE" ("BEREGNINGSGRUNNLAG_ID")  ;

  CREATE INDEX "IDX_BG_ANDEL_ARBEIDSFORHOLD_01" ON "BG_ANDEL_ARBEIDSFORHOLD" ("BG_ANDEL_ID")  ;

  CREATE INDEX "IDX_BG_ANDEL_ARBEIDSFORHOLD_11" ON "BG_ANDEL_ARBEIDSFORHOLD" ("ARBEIDSFORHOLD_INTERN_ID")  ;

  CREATE INDEX "IDX_BG_ANDEL_ARBEIDSFORHOLD_03" ON "BG_ANDEL_ARBEIDSFORHOLD" ("ARBEIDSGIVER_ORGNR")  ;

  CREATE INDEX "IDX_BR_KONSEKVENS_YTELSE_1" ON "BEHANDLING_RESULTAT_YT_KONSEK" ("BEHANDLING_RESULTAT_ID")  ;

  CREATE INDEX "IDX_MEDLEMSKAP_VL_1" ON "MEDLEMSKAP_VURDERING_LOPENDE" ("VURDERT_PERIODE_ID")  ;

  CREATE INDEX "IDX_MEDLEMSKAP_VL_2" ON "MEDLEMSKAP_VURDERING_LOPENDE" ("MANUELL_VURD")  ;

  CREATE INDEX "IDX_KLAGE_RESULTAT_2" ON "KLAGE_RESULTAT" ("PAAKLAGD_BEHANDLING_ID")  ;

  CREATE INDEX "IDX_KLAGE_RESULTAT_1" ON "KLAGE_RESULTAT" ("KLAGE_BEHANDLING_ID")  ;

  CREATE INDEX "IDX_KLAGE_FORMKRAV_1" ON "KLAGE_FORMKRAV" ("KLAGE_RESULTAT_ID")  ;

  CREATE INDEX "IDX_TILBAKEKREVING_VALG_1" ON "TILBAKEKREVING_VALG" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_TILBAKEKREVING_VALG_2" ON "TILBAKEKREVING_VALG" ("VIDERE_BEHANDLING")  ;

  CREATE INDEX "IDX_BEH_OVERLAPP_INFOTRYGD_01" ON "BEHANDLING_OVERLAPP_INFOTRYGD" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_BG_ARBEIDSTAKER_ANDEL" ON "BG_ARBEIDSTAKER_ANDEL" ("BG_PR_STATUS_ANDEL_ID")  ;

  CREATE INDEX "IDX_BG_FRILANS_ANDEL" ON "BG_FRILANS_ANDEL" ("BG_PR_STATUS_ANDEL_ID")  ;

  CREATE INDEX "IDX_BG_AKTIVITET_04" ON "BG_AKTIVITET" ("ARBEIDSGIVER_ORGNR")  ;

  CREATE INDEX "IDX_BG_AKTIVITET_01" ON "BG_AKTIVITET" ("BG_AKTIVITETER_ID")  ;

  CREATE INDEX "IDX_BG_AKTIVITET_11" ON "BG_AKTIVITET" ("ARBEIDSFORHOLD_INTERN_ID")  ;

  CREATE UNIQUE INDEX "IDX_ETTERKONTROLL_1" ON "ETTERKONTROLL" ("FAGSAK_ID")  ;

  CREATE INDEX "IDX_ETTERKONTROLL_2" ON "ETTERKONTROLL" ("KONTROLL_TYPE")  ;

  CREATE INDEX "IDX_RISIKOKLASSIFISERING_1" ON "RISIKOKLASSIFISERING" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_RISIKOKLASSIFISERING_2" ON "RISIKOKLASSIFISERING" ("KONTROLL_RESULTAT")  ;

  CREATE INDEX "IDX_RISIKOKLASSIFISERING_3" ON "RISIKOKLASSIFISERING" ("FARESIGNAL_VURDERING")  ;

  CREATE INDEX "IDX_TILBAKEKREVING_INNTREKK_1" ON "TILBAKEKREVING_INNTREKK" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_OKO_OMPOSTERING_116_1" ON "OKO_OMPOSTERING_116" ("OKO_OPPDRAG_110_ID")  ;

  CREATE INDEX "IDX_SVP_TILRETTELEGGING_1" ON "SVP_TILRETTELEGGING" ("ARBEIDSFORHOLD_INTERN_ID")  ;

  CREATE INDEX "IDX_TILRETTELEGGING_2" ON "SVP_TILRETTELEGGING" ("SVP_TILRETTELEGGINGER_ID")  ;

  CREATE INDEX "IDX_SVP_GRUNNLAG_1" ON "SVP_GRUNNLAG" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_SVP_GRUNNLAG_2" ON "SVP_GRUNNLAG" ("OPPRINNELINGE_TRLG_ID")  ;

  CREATE INDEX "IDX_SVP_GRUNNLAG_3" ON "SVP_GRUNNLAG" ("OVERSTYRTE_TRLG_ID")  ;

  CREATE INDEX "IDX_SVP_UTTAK_RESULTAT_1" ON "SVP_UTTAK_RESULTAT" ("BEHANDLING_RESULTAT_ID")  ;

  CREATE INDEX "IDX_SVP_UTTAK_ARBEIDSFORHOLD_3" ON "SVP_UTTAK_ARBEIDSFORHOLD" ("ARBEIDSGIVER_ORGNR")  ;

  CREATE INDEX "IDX_SVP_UTTAK_ARBEIDSFORHOLD_2" ON "SVP_UTTAK_ARBEIDSFORHOLD" ("ARBEIDSFORHOLD_RESULTAT_AARSAK")  ;

  CREATE INDEX "IDX_SVP_UTTAK_ARBEIDSFORHOLD_1" ON "SVP_UTTAK_ARBEIDSFORHOLD" ("SVP_UTTAK_RESULTAT_ID")  ;

  CREATE INDEX "IDX_SVP_UTTAK_ARBEIDSFORH_11" ON "SVP_UTTAK_ARBEIDSFORHOLD" ("ARBEIDSFORHOLD_INTERN_ID")  ;

  CREATE INDEX "IDX_SVP_UTTAK_PERIODE_1" ON "SVP_UTTAK_PERIODE" ("SVP_UTTAK_ARBEIDSFORHOLD_ID")  ;

  CREATE INDEX "IDX_SVP_UTTAK_PERIODE_2" ON "SVP_UTTAK_PERIODE" ("PERIODE_RESULTAT_TYPE")  ;

  CREATE INDEX "IDX_SVP_UTTAK_PERIODE_3" ON "SVP_UTTAK_PERIODE" ("PERIODE_RESULTAT_AARSAK")  ;

  CREATE INDEX "IDX_BA_OVERSTYRING_01" ON "BG_AKTIVITET_OVERSTYRING" ("BA_OVERSTYRINGER_ID")  ;

  CREATE INDEX "IDX_BA_OVERSTYRING_02" ON "BG_AKTIVITET_OVERSTYRING" ("ARBEIDSGIVER_ORGNR")  ;

  CREATE INDEX "IDX_BG_AKTIV_OVERSTYRING_11" ON "BG_AKTIVITET_OVERSTYRING" ("ARBEIDSFORHOLD_INTERN_ID")  ;

  CREATE INDEX "IDX_TILRETTELEGGING_FOM_1" ON "TILRETTELEGGING_FOM" ("SVP_TILRETTELEGGING_ID")  ;

  CREATE INDEX "IDX_ANKE_RESULTAT_1" ON "ANKE_RESULTAT" ("ANKE_BEHANDLING_ID")  ;

  CREATE INDEX "IDX_ANKE_RESULTAT_2" ON "ANKE_RESULTAT" ("PAA_ANKET_BEHANDLING_ID")  ;

  CREATE INDEX "IDX_ANKE_VURDERING_RESULTAT_1" ON "ANKE_VURDERING_RESULTAT" ("ANKE_RESULTAT_ID")  ;

  CREATE INDEX "IDX_ANKE_VURDERING_RESULTAT_2" ON "ANKE_VURDERING_RESULTAT" ("ANKEVURDERING")  ;

  CREATE INDEX "IDX_ANKE_VURDERING_RESULTAT_3" ON "ANKE_VURDERING_RESULTAT" ("ANKE_OMGJOER_AARSAK")  ;

  CREATE INDEX "IDX_ANKE_VURDERING_RESULTAT_4" ON "ANKE_VURDERING_RESULTAT" ("ANKE_VURDERING_OMGJOER")  ;

  CREATE INDEX "IDX_BR_OVERSTYRING_01" ON "BG_REFUSJON_OVERSTYRING" ("BR_OVERSTYRINGER_ID")  ;

  CREATE INDEX "IDX_BR_OVERSTYRING_02" ON "BG_REFUSJON_OVERSTYRING" ("ARBEIDSGIVER_ORGNR")  ;

  CREATE INDEX "IDX_BR_OVERSTYRING_03" ON "BG_REFUSJON_OVERSTYRING" ("ARBEIDSGIVER_AKTOR_ID")  ;

  CREATE INDEX "IDX_BG_PERIODE_RS_02" ON "BG_PERIODE_REGEL_SPORING" ("REGEL_TYPE")  ;

  CREATE INDEX "IDX_BG_PERIODE_RS_01" ON "BG_PERIODE_REGEL_SPORING" ("BG_PERIODE_ID")  ;

  CREATE INDEX "IDX_BG_RS_01" ON "BG_REGEL_SPORING" ("BG_ID")  ;

  CREATE INDEX "IDX_BG_RS_02" ON "BG_REGEL_SPORING" ("REGEL_TYPE")  ;

  CREATE INDEX "IDX_ABAKUS_INN_LOGG_01" ON "ABAKUS_INNHENTING_LOGG" ("BEHANDLING_ID")  ;

  CREATE INDEX "IDX_ABAKUS_INN_LOGG_02" ON "ABAKUS_INNHENTING_LOGG" ("GRUNNLAG_UUID")  ;

  CREATE INDEX "IDX_BG_SG_PR_STATUS_01" ON "BG_SG_PR_STATUS" ("BEREGNINGSGRUNNLAG_ID")  ;
-- REF_CONSTRAINT

  ALTER TABLE "MEDLEMSKAP_OPPG_LAND" ADD CONSTRAINT "FK_MEDLEMSKAP_OPPG_LAND_1" FOREIGN KEY ("MEDLEMSKAP_OPPG_TILKNYT_ID")
	  REFERENCES "MEDLEMSKAP_OPPG_TILKNYT" ("ID") ENABLE;

  ALTER TABLE "BG_PERIODE_AARSAK" ADD CONSTRAINT "FK_BG_PERIODE_AARSAK_1" FOREIGN KEY ("BG_PERIODE_ID")
	  REFERENCES "BEREGNINGSGRUNNLAG_PERIODE" ("ID") ENABLE;

  ALTER TABLE "KODELISTE_RELASJON" ADD CONSTRAINT "FK_KODELISTE_REL_01" FOREIGN KEY ("KODE1", "KODEVERK1")
	  REFERENCES "KODELISTE" ("KODE", "KODEVERK") ENABLE;
  ALTER TABLE "KODELISTE_RELASJON" ADD CONSTRAINT "FK_KODELISTE_REL_02" FOREIGN KEY ("KODE2", "KODEVERK2")
	  REFERENCES "KODELISTE" ("KODE", "KODEVERK") ENABLE;

  ALTER TABLE "GR_PERSONOPPLYSNING" ADD CONSTRAINT "FK_GR_PERSONOPPL_ANNE_PRT" FOREIGN KEY ("SO_ANNEN_PART_ID")
	  REFERENCES "SO_ANNEN_PART" ("ID") ENABLE;
  ALTER TABLE "GR_PERSONOPPLYSNING" ADD CONSTRAINT "FK_GR_PERSONOPPL_BEH" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;
  ALTER TABLE "GR_PERSONOPPLYSNING" ADD CONSTRAINT "FK_GR_PERSONOPPLYSNING_03" FOREIGN KEY ("REGISTRERT_INFORMASJON_ID")
	  REFERENCES "PO_INFORMASJON" ("ID") ENABLE;
  ALTER TABLE "GR_PERSONOPPLYSNING" ADD CONSTRAINT "FK_GR_PERSONOPPLYSNING_04" FOREIGN KEY ("OVERSTYRT_INFORMASJON_ID")
	  REFERENCES "PO_INFORMASJON" ("ID") ENABLE;

  ALTER TABLE "GR_VERGE" ADD CONSTRAINT "FK_GR_VERGE_BEH" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;
  ALTER TABLE "GR_VERGE" ADD CONSTRAINT "FK_GR_VERGE_VID" FOREIGN KEY ("VERGE_ID")
	  REFERENCES "VERGE" ("ID") ENABLE;

  ALTER TABLE "BG_ANDEL_ARBEIDSFORHOLD" ADD CONSTRAINT "FK_BG_ANDEL_ARBEIDSFORHOLD_1" FOREIGN KEY ("BG_ANDEL_ID")
	  REFERENCES "BG_PR_STATUS_OG_ANDEL" ("ID") ENABLE;

  ALTER TABLE "GR_MEDLEMSKAP" ADD CONSTRAINT "FK_GR_MEDL_BEH" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;
  ALTER TABLE "GR_MEDLEMSKAP" ADD CONSTRAINT "FK_GR_MEDL_TILKN_HJEM" FOREIGN KEY ("OPPGITT_ID")
	  REFERENCES "MEDLEMSKAP_OPPG_TILKNYT" ("ID") ENABLE;
  ALTER TABLE "GR_MEDLEMSKAP" ADD CONSTRAINT "FK_GR_MEDL_MEDL" FOREIGN KEY ("VURDERING_ID")
	  REFERENCES "MEDLEMSKAP_VURDERING" ("ID") ENABLE;
  ALTER TABLE "GR_MEDLEMSKAP" ADD CONSTRAINT "FK_GR_MEDL_REG_MEDL" FOREIGN KEY ("REGISTRERT_ID")
	  REFERENCES "MEDLEMSKAP_REGISTRERT" ("ID") ENABLE;

  ALTER TABLE "PROSESS_TASK_TYPE" ADD CONSTRAINT "FK_PROSESS_TASK_TYPE_1" FOREIGN KEY ("FEILHANDTERING_ALGORITME")
	  REFERENCES "PROSESS_TASK_FEILHAND" ("KODE") ENABLE;

  ALTER TABLE "OPPDRAG_KVITTERING" ADD CONSTRAINT "FK_OPPDRAG_KVITTERING_1" FOREIGN KEY ("OPPDRAG_110_ID")
	  REFERENCES "OKO_OPPDRAG_110" ("ID") ENABLE;

  ALTER TABLE "GR_FAMILIE_HENDELSE" ADD CONSTRAINT "FK_GR_FAMILIE_HENDELSE_1" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;
  ALTER TABLE "GR_FAMILIE_HENDELSE" ADD CONSTRAINT "FK_GR_FAMILIE_HENDELSE_2" FOREIGN KEY ("SOEKNAD_FAMILIE_HENDELSE_ID")
	  REFERENCES "FH_FAMILIE_HENDELSE" ("ID") ENABLE;
  ALTER TABLE "GR_FAMILIE_HENDELSE" ADD CONSTRAINT "FK_GR_FAMILIE_HENDELSE_3" FOREIGN KEY ("BEKREFTET_FAMILIE_HENDELSE_ID")
	  REFERENCES "FH_FAMILIE_HENDELSE" ("ID") ENABLE;
  ALTER TABLE "GR_FAMILIE_HENDELSE" ADD CONSTRAINT "FK_GR_FAMILIE_HENDELSE_4" FOREIGN KEY ("OVERSTYRT_FAMILIE_HENDELSE_ID")
	  REFERENCES "FH_FAMILIE_HENDELSE" ("ID") ENABLE;

  ALTER TABLE "FH_TERMINBEKREFTELSE" ADD CONSTRAINT "FK_TERMINBEKREFTELSE_1" FOREIGN KEY ("FAMILIE_HENDELSE_ID")
	  REFERENCES "FH_FAMILIE_HENDELSE" ("ID") ENABLE;

  ALTER TABLE "FH_ADOPSJON" ADD CONSTRAINT "FK_ADOPSJON_1" FOREIGN KEY ("FAMILIE_HENDELSE_ID")
	  REFERENCES "FH_FAMILIE_HENDELSE" ("ID") ENABLE;

  ALTER TABLE "FH_UIDENTIFISERT_BARN" ADD CONSTRAINT "FK_UIDENTIFISERT_BARN_1" FOREIGN KEY ("FAMILIE_HENDELSE_ID")
	  REFERENCES "FH_FAMILIE_HENDELSE" ("ID") ENABLE;

  ALTER TABLE "KODELISTE" ADD CONSTRAINT "FK_KODELISTE_01" FOREIGN KEY ("KODEVERK")
	  REFERENCES "KODEVERK" ("KODE") ENABLE;

  ALTER TABLE "VURDER_AARSAK_TTVURDERING" ADD CONSTRAINT "FK_VURDER_AARSAK_TTVURDERING_1" FOREIGN KEY ("TOTRINNSVURDERING_ID")
	  REFERENCES "TOTRINNSVURDERING" ("ID") ENABLE;

  ALTER TABLE "TOTRINNSVURDERING" ADD CONSTRAINT "FK_TOTRINNSVURDERING_2" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;

  ALTER TABLE "KODELISTE_NAVN_I18N" ADD CONSTRAINT "FK_KODELISTE_I18N_01" FOREIGN KEY ("KL_KODE", "KL_KODEVERK")
	  REFERENCES "KODELISTE" ("KODE", "KODEVERK") ENABLE;

  ALTER TABLE "FAGSAK_PROSESS_TASK" ADD CONSTRAINT "FK_FAGSAK_PROSESS_TASK_1" FOREIGN KEY ("FAGSAK_ID")
	  REFERENCES "FAGSAK" ("ID") ENABLE;
  ALTER TABLE "FAGSAK_PROSESS_TASK" ADD CONSTRAINT "FK_FAGSAK_PROSESS_TASK_2" FOREIGN KEY ("PROSESS_TASK_ID")
	  REFERENCES "PROSESS_TASK" ("ID") ENABLE;
  ALTER TABLE "FAGSAK_PROSESS_TASK" ADD CONSTRAINT "FK_FAGSAK_PROSESS_TASK_3" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;

  ALTER TABLE "BEHANDLING_RESULTAT_YT_KONSEK" ADD CONSTRAINT "FK_BR_KONSEKVENS_YTELSE_1" FOREIGN KEY ("BEHANDLING_RESULTAT_ID")
	  REFERENCES "BEHANDLING_RESULTAT" ("ID") ENABLE;

  ALTER TABLE "GR_SOEKNAD" ADD CONSTRAINT "FK_GR_SOEKNAD_1" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;
  ALTER TABLE "GR_SOEKNAD" ADD CONSTRAINT "FK_GR_SOEKNAD_2" FOREIGN KEY ("SOEKNAD_ID")
	  REFERENCES "SO_SOEKNAD" ("ID") ENABLE;

  ALTER TABLE "BG_FAKTA_BER_TILFELLE" ADD CONSTRAINT "FK_BG_FAKTA_BER_TILFELLE_1" FOREIGN KEY ("BEREGNINGSGRUNNLAG_ID")
	  REFERENCES "BEREGNINGSGRUNNLAG" ("ID") ENABLE;

  ALTER TABLE "KLAGE_RESULTAT" ADD CONSTRAINT "FK_KLAGE_RESULTAT_1" FOREIGN KEY ("KLAGE_BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;
  ALTER TABLE "KLAGE_RESULTAT" ADD CONSTRAINT "FK_KLAGE_RESULTAT_2" FOREIGN KEY ("PAAKLAGD_BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;

  ALTER TABLE "KLAGE_FORMKRAV" ADD CONSTRAINT "FK_KLAGE_FORMKRAV_1" FOREIGN KEY ("KLAGE_RESULTAT_ID")
	  REFERENCES "KLAGE_RESULTAT" ("ID") ENABLE;

  ALTER TABLE "TILRETTELEGGING_FOM" ADD CONSTRAINT "FK_TILRETTELEGGING_FOM_1" FOREIGN KEY ("SVP_TILRETTELEGGING_ID")
	  REFERENCES "SVP_TILRETTELEGGING" ("ID") ENABLE;

  ALTER TABLE "AKSJONSPUNKT" ADD CONSTRAINT "FK_AKSJONSPUNKT_2" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;

  ALTER TABLE "BG_PERIODE_REGEL_SPORING" ADD CONSTRAINT "FK_BG_PERIODE_REGEL_SPORING_01" FOREIGN KEY ("BG_PERIODE_ID")
	  REFERENCES "BEREGNINGSGRUNNLAG_PERIODE" ("ID") ENABLE;

  ALTER TABLE "FAGSAK_RELASJON" ADD CONSTRAINT "FK_FAGSAK_RELASJON_4" FOREIGN KEY ("OVERSTYRT_KONTO_BEREGNING_ID")
	  REFERENCES "STOENADSKONTOBEREGNING" ("ID") ENABLE;
  ALTER TABLE "FAGSAK_RELASJON" ADD CONSTRAINT "FK_FAGSAK_RELASJON_1" FOREIGN KEY ("FAGSAK_EN_ID")
	  REFERENCES "FAGSAK" ("ID") ENABLE;
  ALTER TABLE "FAGSAK_RELASJON" ADD CONSTRAINT "FK_FAGSAK_RELASJON_2" FOREIGN KEY ("FAGSAK_TO_ID")
	  REFERENCES "FAGSAK" ("ID") ENABLE;
  ALTER TABLE "FAGSAK_RELASJON" ADD CONSTRAINT "FK_FAGSAK_RELASJON_3" FOREIGN KEY ("KONTO_BEREGNING_ID")
	  REFERENCES "STOENADSKONTOBEREGNING" ("ID") ENABLE;

  ALTER TABLE "FAGSAK" ADD CONSTRAINT "FK_FAGSAK_3" FOREIGN KEY ("BRUKER_ID")
	  REFERENCES "BRUKER" ("ID") ENABLE;

  ALTER TABLE "JOURNALPOST" ADD CONSTRAINT "FK_JOURNALPOST" FOREIGN KEY ("FAGSAK_ID")
	  REFERENCES "FAGSAK" ("ID") ENABLE;

  ALTER TABLE "BEHANDLING" ADD CONSTRAINT "FK_BEHANDLING_1" FOREIGN KEY ("FAGSAK_ID")
	  REFERENCES "FAGSAK" ("ID") ENABLE;

  ALTER TABLE "OPPGAVE_BEHANDLING_KOBLING" ADD CONSTRAINT "FK_OPPGAVE_BEH_KOBLING_2" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;

  ALTER TABLE "VILKAR_RESULTAT" ADD CONSTRAINT "FK_INNGANGSVILKAR_RESULTAT_2" FOREIGN KEY ("ORIGINAL_BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;

  ALTER TABLE "VILKAR" ADD CONSTRAINT "FK_VILKAR_3" FOREIGN KEY ("VILKAR_RESULTAT_ID")
	  REFERENCES "VILKAR_RESULTAT" ("ID") ENABLE;

  ALTER TABLE "BR_LEGACY_ES_BEREGNING" ADD CONSTRAINT "FK_BEREGNING_1" FOREIGN KEY ("BEREGNING_RESULTAT_ID")
	  REFERENCES "BR_LEGACY_ES_BEREGNING_RES" ("ID") ENABLE;

  ALTER TABLE "BEHANDLING_RESULTAT" ADD CONSTRAINT "FK_BEHANDLING_RESULTAT_1" FOREIGN KEY ("INNGANGSVILKAR_RESULTAT_ID")
	  REFERENCES "VILKAR_RESULTAT" ("ID") ENABLE;
  ALTER TABLE "BEHANDLING_RESULTAT" ADD CONSTRAINT "FK_BEHANDLING_RESULTAT_2" FOREIGN KEY ("BEREGNING_RESULTAT_ID")
	  REFERENCES "BR_LEGACY_ES_BEREGNING_RES" ("ID") ENABLE;
  ALTER TABLE "BEHANDLING_RESULTAT" ADD CONSTRAINT "FK_BEHANDLING_RESULTAT_3" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;

  ALTER TABLE "BEHANDLING_VEDTAK" ADD CONSTRAINT "FK_BEHANDLING_VEDTAK_1" FOREIGN KEY ("BEHANDLING_RESULTAT_ID")
	  REFERENCES "BEHANDLING_RESULTAT" ("ID") ENABLE;

  ALTER TABLE "HISTORIKKINNSLAG" ADD CONSTRAINT "FK_HISTORIKKINNSLAG_3" FOREIGN KEY ("FAGSAK_ID")
	  REFERENCES "FAGSAK" ("ID") ENABLE;
  ALTER TABLE "HISTORIKKINNSLAG" ADD CONSTRAINT "FK_BEHANDLING_ID" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;

  ALTER TABLE "HISTORIKKINNSLAG_DOK_LINK" ADD CONSTRAINT "FK_HISTORIKKINNSLAG_ID" FOREIGN KEY ("HISTORIKKINNSLAG_ID")
	  REFERENCES "HISTORIKKINNSLAG" ("ID") ENABLE;

  ALTER TABLE "MOTTATT_DOKUMENT" ADD CONSTRAINT "FK_MOTTATT_DOKUMENT_02" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;
  ALTER TABLE "MOTTATT_DOKUMENT" ADD CONSTRAINT "FK_MOTTATT_DOKUMENT_04" FOREIGN KEY ("FAGSAK_ID")
	  REFERENCES "FAGSAK" ("ID") ENABLE;

  ALTER TABLE "SOEKNAD_VEDLEGG" ADD CONSTRAINT "FK_VEDLEGG_2" FOREIGN KEY ("SOEKNAD_ID")
	  REFERENCES "SO_SOEKNAD" ("ID") ENABLE;

  ALTER TABLE "OKO_OPPDRAG_110" ADD CONSTRAINT "FK_OKO_OPPDRAG_110_1" FOREIGN KEY ("OPPDRAGS_KONTROLL_ID")
	  REFERENCES "OPPDRAG_KONTROLL" ("ID") ENABLE;
  ALTER TABLE "OKO_OPPDRAG_110" ADD CONSTRAINT "FK_OKO_OPPDRAG_110_2" FOREIGN KEY ("AVSTEMMING115_ID")
	  REFERENCES "OKO_AVSTEMMING_115" ("ID") ENABLE;

  ALTER TABLE "OKO_OPPDRAG_ENHET_120" ADD CONSTRAINT "FK_OKO_OPPDRAG_ENHET_120_1" FOREIGN KEY ("OPPDRAG110_ID")
	  REFERENCES "OKO_OPPDRAG_110" ("ID") ENABLE;

  ALTER TABLE "OKO_OPPDRAG_LINJE_150" ADD CONSTRAINT "FK_OKO_OPPDRAG_LINJE_150_1" FOREIGN KEY ("OPPDRAG110_ID")
	  REFERENCES "OKO_OPPDRAG_110" ("ID") ENABLE;

  ALTER TABLE "OKO_ATTESTANT_180" ADD CONSTRAINT "FK_OKO_ATTESTANT_180_1" FOREIGN KEY ("OPPDRAGS_LINJE_150_ID")
	  REFERENCES "OKO_OPPDRAG_LINJE_150" ("ID") ENABLE;

  ALTER TABLE "BEHANDLING_STEG_TILSTAND" ADD CONSTRAINT "FK_BEHANDLING_STEG_TILSTAND_1" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;

  ALTER TABLE "MEDLEMSKAP_PERIODER" ADD CONSTRAINT "FK_MEDLEMSKAP_PERIODER_1" FOREIGN KEY ("MEDLEMSKAP_REGISTRERT_ID")
	  REFERENCES "MEDLEMSKAP_REGISTRERT" ("ID") ENABLE;

  ALTER TABLE "BEHANDLING_ARSAK" ADD CONSTRAINT "FK_BEHANDLING_ARSAK_2" FOREIGN KEY ("ORIGINAL_BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;
  ALTER TABLE "BEHANDLING_ARSAK" ADD CONSTRAINT "FK_BEHANDLING_ARSAK_1" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;

  ALTER TABLE "VERGE" ADD CONSTRAINT "FK_VERGE_ORGANISASJON" FOREIGN KEY ("ORGANISASJON_ID")
	  REFERENCES "VERGE_ORGANISASJON" ("ID") ENABLE;
  ALTER TABLE "VERGE" ADD CONSTRAINT "FK_VERGE_1" FOREIGN KEY ("BRUKER_ID")
	  REFERENCES "BRUKER" ("ID") ENABLE;

  ALTER TABLE "KLAGE_VURDERING_RESULTAT" ADD CONSTRAINT "FK_KLAGE_VURDERING_RESULTAT_6" FOREIGN KEY ("KLAGE_RESULTAT_ID")
	  REFERENCES "KLAGE_RESULTAT" ("ID") ENABLE;

  ALTER TABLE "BEREGNINGSGRUNNLAG_PERIODE" ADD CONSTRAINT "FK_BG_PERIODE_1" FOREIGN KEY ("BEREGNINGSGRUNNLAG_ID")
	  REFERENCES "BEREGNINGSGRUNNLAG" ("ID") ENABLE;

  ALTER TABLE "BG_PR_STATUS_OG_ANDEL" ADD CONSTRAINT "FK_BG_PR_STATUS_OG_ANDEL_1" FOREIGN KEY ("BG_PERIODE_ID")
	  REFERENCES "BEREGNINGSGRUNNLAG_PERIODE" ("ID") ENABLE;

  ALTER TABLE "SAMMENLIGNINGSGRUNNLAG" ADD CONSTRAINT "FK_SAMMENLIGNINGSGRUNNLAG_1" FOREIGN KEY ("BEREGNINGSGRUNNLAG_ID")
	  REFERENCES "BEREGNINGSGRUNNLAG" ("ID") ENABLE;

  ALTER TABLE "BG_AKTIVITET_STATUS" ADD CONSTRAINT "FK_BG_AKTIVITET_STATUS_1" FOREIGN KEY ("BEREGNINGSGRUNNLAG_ID")
	  REFERENCES "BEREGNINGSGRUNNLAG" ("ID") ENABLE;

  ALTER TABLE "STOENADSKONTO" ADD CONSTRAINT "FK_STOENADSKONTO_1" FOREIGN KEY ("STOENADSKONTOBEREGNING_ID")
	  REFERENCES "STOENADSKONTOBEREGNING" ("ID") ENABLE;

  ALTER TABLE "INNSYN" ADD CONSTRAINT "FK_INNSYN_BEH" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;

  ALTER TABLE "GR_BEREGNINGSGRUNNLAG" ADD CONSTRAINT "FK_GR_BEREGNINGSGRUNNLAG_3" FOREIGN KEY ("REGISTER_AKTIVITETER_ID")
	  REFERENCES "BG_AKTIVITETER" ("ID") ENABLE;
  ALTER TABLE "GR_BEREGNINGSGRUNNLAG" ADD CONSTRAINT "FK_GR_BEREGNINGSGRUNNLAG_4" FOREIGN KEY ("SAKSBEHANDLET_AKTIVITETER_ID")
	  REFERENCES "BG_AKTIVITETER" ("ID") ENABLE;
  ALTER TABLE "GR_BEREGNINGSGRUNNLAG" ADD CONSTRAINT "FK_GR_BEREGNINGSGRUNNLAG_1" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;
  ALTER TABLE "GR_BEREGNINGSGRUNNLAG" ADD CONSTRAINT "FK_GR_BEREGNINGSGRUNNLAG_2" FOREIGN KEY ("BEREGNINGSGRUNNLAG_ID")
	  REFERENCES "BEREGNINGSGRUNNLAG" ("ID") ENABLE;
  ALTER TABLE "GR_BEREGNINGSGRUNNLAG" ADD CONSTRAINT "FK_GR_BEREGNINGSGRUNNLAG_5" FOREIGN KEY ("BA_OVERSTYRINGER_ID")
	  REFERENCES "BG_AKTIVITET_OVERSTYRINGER" ("ID") ENABLE;
  ALTER TABLE "GR_BEREGNINGSGRUNNLAG" ADD CONSTRAINT "FK_GR_BEREGNINGSGRUNNLAG_6" FOREIGN KEY ("BR_OVERSTYRINGER_ID")
	  REFERENCES "BG_REFUSJON_OVERSTYRINGER" ("ID") ENABLE;

  ALTER TABLE "YF_FORDELING_PERIODE" ADD CONSTRAINT "FK_SO_FORDELING_PERIODE_4" FOREIGN KEY ("FORDELING_ID")
	  REFERENCES "YF_FORDELING" ("ID") ENABLE;

  ALTER TABLE "GR_YTELSES_FORDELING" ADD CONSTRAINT "FK_GR_YTELSES_FORDELING_3" FOREIGN KEY ("SO_DEKNINGSGRAD_ID")
	  REFERENCES "SO_DEKNINGSGRAD" ("ID") ENABLE;
  ALTER TABLE "GR_YTELSES_FORDELING" ADD CONSTRAINT "FK_GR_YTELSES_FORDELING_4" FOREIGN KEY ("SO_FORDELING_ID")
	  REFERENCES "YF_FORDELING" ("ID") ENABLE;
  ALTER TABLE "GR_YTELSES_FORDELING" ADD CONSTRAINT "FK_GR_YTELSES_FORDELING_7" FOREIGN KEY ("OVERSTYRT_FORDELING_ID")
	  REFERENCES "YF_FORDELING" ("ID") ENABLE;
  ALTER TABLE "GR_YTELSES_FORDELING" ADD CONSTRAINT "FK_YF_DOKUMENTASJON_PERIODE_12" FOREIGN KEY ("ANNEN_FORELDER_HAR_RETT_ID")
	  REFERENCES "YF_DOKUMENTASJON_PERIODER" ("ID") ENABLE;
  ALTER TABLE "GR_YTELSES_FORDELING" ADD CONSTRAINT "FK_GR_YTELSES_FORDELING_1" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;
  ALTER TABLE "GR_YTELSES_FORDELING" ADD CONSTRAINT "FK_GR_YTELSES_FORDELING_2" FOREIGN KEY ("SO_RETTIGHET_ID")
	  REFERENCES "SO_RETTIGHET" ("ID") ENABLE;
  ALTER TABLE "GR_YTELSES_FORDELING" ADD CONSTRAINT "FK_GR_YTELSES_FORDELING_10" FOREIGN KEY ("JUSTERT_FORDELING_ID")
	  REFERENCES "YF_FORDELING" ("ID") ENABLE;
  ALTER TABLE "GR_YTELSES_FORDELING" ADD CONSTRAINT "FK_GR_YTELSES_FORDELING_9" FOREIGN KEY ("YF_AVKLART_DATO_ID")
	  REFERENCES "YF_AVKLART_DATO" ("ID") ENABLE;
  ALTER TABLE "GR_YTELSES_FORDELING" ADD CONSTRAINT "FK_YF_DOKUMENTASJON_PERIODE_9" FOREIGN KEY ("UTENOMSORG_ID")
	  REFERENCES "YF_DOKUMENTASJON_PERIODER" ("ID") ENABLE;
  ALTER TABLE "GR_YTELSES_FORDELING" ADD CONSTRAINT "FK_YF_DOKUMENTASJON_PERIODE_10" FOREIGN KEY ("ALENEOMSORG_ID")
	  REFERENCES "YF_DOKUMENTASJON_PERIODER" ("ID") ENABLE;
  ALTER TABLE "GR_YTELSES_FORDELING" ADD CONSTRAINT "FK_YF_DOKUMENTASJON_PERIODE_11" FOREIGN KEY ("UTTAK_DOKUMENTASJON_ID")
	  REFERENCES "YF_DOKUMENTASJON_PERIODER" ("ID") ENABLE;

  ALTER TABLE "OPPTJENING" ADD CONSTRAINT "FK_OPPTJENING_1" FOREIGN KEY ("VILKAR_RESULTAT_ID")
	  REFERENCES "VILKAR_RESULTAT" ("ID") ENABLE;

  ALTER TABLE "OPPTJENING_AKTIVITET" ADD CONSTRAINT "FK_OPPTJENING_AKTIVITET" FOREIGN KEY ("OPPTJENINGSPERIODE_ID")
	  REFERENCES "OPPTJENING" ("ID") ENABLE;

  ALTER TABLE "INNSYN_DOKUMENT" ADD CONSTRAINT "FK_INNSYN_DOKUMENT_01" FOREIGN KEY ("INNSYN_ID")
	  REFERENCES "INNSYN" ("ID") ENABLE;

  ALTER TABLE "BR_PERIODE" ADD CONSTRAINT "FK_BR_PERIODE_1" FOREIGN KEY ("BEREGNINGSRESULTAT_FP_ID")
	  REFERENCES "BR_BEREGNINGSRESULTAT" ("ID") ENABLE;

  ALTER TABLE "BR_ANDEL" ADD CONSTRAINT "FK_BEREGNINGSRESULTAT_ANDEL_1" FOREIGN KEY ("BR_PERIODE_ID")
	  REFERENCES "BR_PERIODE" ("ID") ENABLE;

  ALTER TABLE "BR_RESULTAT_BEHANDLING" ADD CONSTRAINT "FK_RES_BEREGNINGSRESULTAT_FP_1" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;

  ALTER TABLE "UTTAKSPERIODEGRENSE" ADD CONSTRAINT "FK_UTTAKSPERIODEGRENSE" FOREIGN KEY ("BEHANDLING_RESULTAT_ID")
	  REFERENCES "BEHANDLING_RESULTAT" ("ID") ENABLE;

  ALTER TABLE "HISTORIKKINNSLAG_DEL" ADD CONSTRAINT "FK_HISTORIKKINNSLAG_DEL_1" FOREIGN KEY ("HISTORIKKINNSLAG_ID")
	  REFERENCES "HISTORIKKINNSLAG" ("ID") ENABLE;

  ALTER TABLE "HISTORIKKINNSLAG_FELT" ADD CONSTRAINT "FK_HISTORIKKINNSLAG_FELT_1" FOREIGN KEY ("HISTORIKKINNSLAG_DEL_ID")
	  REFERENCES "HISTORIKKINNSLAG_DEL" ("ID") ENABLE;

  ALTER TABLE "OKO_REFUSJONSINFO_156" ADD CONSTRAINT "FK_OKO_REFUSJONSINFO_156_1" FOREIGN KEY ("OPPDRAGS_LINJE_150_ID")
	  REFERENCES "OKO_OPPDRAG_LINJE_150" ("ID") ENABLE;

  ALTER TABLE "OKO_GRAD_170" ADD CONSTRAINT "FK_OKO_GRAD_170_1" FOREIGN KEY ("OPPDRAGS_LINJE_150_ID")
	  REFERENCES "OKO_OPPDRAG_LINJE_150" ("ID") ENABLE;

  ALTER TABLE "YF_DOKUMENTASJON_PERIODE" ADD CONSTRAINT "FK_YF_DOKUMENTASJON_PERIODE_1" FOREIGN KEY ("PERIODER_ID")
	  REFERENCES "YF_DOKUMENTASJON_PERIODER" ("ID") ENABLE;

  ALTER TABLE "MEDLEMSKAP_VILKAR_PERIODER" ADD CONSTRAINT "FK_MEDLEMSKAP_VILKAR_PERIODE" FOREIGN KEY ("MEDLEMSKAP_VILKAR_PERIODE_ID")
	  REFERENCES "MEDLEMSKAP_VILKAR_PERIODE" ("ID") ENABLE;

  ALTER TABLE "GR_MEDLEMSKAP_VILKAR_PERIODE" ADD CONSTRAINT "FK_GR_MEDLEMSKAP_VILKAR_PER_1" FOREIGN KEY ("VILKAR_RESULTAT_ID")
	  REFERENCES "VILKAR_RESULTAT" ("ID") ENABLE;
  ALTER TABLE "GR_MEDLEMSKAP_VILKAR_PERIODE" ADD CONSTRAINT "FK_GR_MEDLEMSKAP_VILKAR_PER_2" FOREIGN KEY ("MEDLEMSKAP_VILKAR_PERIODE_ID")
	  REFERENCES "MEDLEMSKAP_VILKAR_PERIODE" ("ID") ENABLE;

  ALTER TABLE "UTTAK_RESULTAT_PERIODE" ADD CONSTRAINT "FK_UTTAK_RESULTAT_PERIODE_02" FOREIGN KEY ("PERIODE_SOKNAD_ID")
	  REFERENCES "UTTAK_RESULTAT_PERIODE_SOKNAD" ("ID") ENABLE;
  ALTER TABLE "UTTAK_RESULTAT_PERIODE" ADD CONSTRAINT "FK_UTTAK_RESULTAT_PERIODE_01" FOREIGN KEY ("UTTAK_RESULTAT_PERIODER_ID")
	  REFERENCES "UTTAK_RESULTAT_PERIODER" ("ID") ENABLE;

  ALTER TABLE "UTTAK_RESULTAT" ADD CONSTRAINT "FK_UTTAK_RESULTAT_1" FOREIGN KEY ("BEHANDLING_RESULTAT_ID")
	  REFERENCES "BEHANDLING_RESULTAT" ("ID") ENABLE;
  ALTER TABLE "UTTAK_RESULTAT" ADD CONSTRAINT "FK_UTTAK_RESULTAT_2" FOREIGN KEY ("OPPRINNELIG_PERIODER_ID")
	  REFERENCES "UTTAK_RESULTAT_PERIODER" ("ID") ENABLE;
  ALTER TABLE "UTTAK_RESULTAT" ADD CONSTRAINT "FK_UTTAK_RESULTAT_3" FOREIGN KEY ("OVERSTYRT_PERIODER_ID")
	  REFERENCES "UTTAK_RESULTAT_PERIODER" ("ID") ENABLE;

  ALTER TABLE "PO_ADRESSE" ADD CONSTRAINT "FK_PO_ADRESSE_2" FOREIGN KEY ("PO_INFORMASJON_ID")
	  REFERENCES "PO_INFORMASJON" ("ID") ENABLE;

  ALTER TABLE "PO_RELASJON" ADD CONSTRAINT "FK_PO_RELASJON_2" FOREIGN KEY ("PO_INFORMASJON_ID")
	  REFERENCES "PO_INFORMASJON" ("ID") ENABLE;

  ALTER TABLE "PO_STATSBORGERSKAP" ADD CONSTRAINT "FK_PO_STATSBORGERSKAP_2" FOREIGN KEY ("PO_INFORMASJON_ID")
	  REFERENCES "PO_INFORMASJON" ("ID") ENABLE;

  ALTER TABLE "PO_PERSONSTATUS" ADD CONSTRAINT "FK_PO_PERSONSTATUS_2" FOREIGN KEY ("PO_INFORMASJON_ID")
	  REFERENCES "PO_INFORMASJON" ("ID") ENABLE;

  ALTER TABLE "PO_PERSONOPPLYSNING" ADD CONSTRAINT "FK_PO_PERSONOPPLYSNING_2" FOREIGN KEY ("PO_INFORMASJON_ID")
	  REFERENCES "PO_INFORMASJON" ("ID") ENABLE;

  ALTER TABLE "UTTAK_RESULTAT_DOK_REGEL" ADD CONSTRAINT "FK_UTTAK_RESULTAT_DOK_REGEL_02" FOREIGN KEY ("UTTAK_RESULTAT_PERIODE_ID")
	  REFERENCES "UTTAK_RESULTAT_PERIODE" ("ID") ENABLE;

  ALTER TABLE "UTTAK_RESULTAT_PERIODE_AKT" ADD CONSTRAINT "FK_UTTAK_RES_PERIODE_AKT_01" FOREIGN KEY ("UTTAK_RESULTAT_PERIODE_ID")
	  REFERENCES "UTTAK_RESULTAT_PERIODE" ("ID") ENABLE;
  ALTER TABLE "UTTAK_RESULTAT_PERIODE_AKT" ADD CONSTRAINT "FK_UTTAK_RES_PERIODE_AKT_02" FOREIGN KEY ("UTTAK_AKTIVITET_ID")
	  REFERENCES "UTTAK_AKTIVITET" ("ID") ENABLE;

  ALTER TABLE "BR_FERIEPENGER" ADD CONSTRAINT "FK_BR_FERIEPENGER_1" FOREIGN KEY ("BEREGNINGSRESULTAT_FP_ID")
	  REFERENCES "BR_BEREGNINGSRESULTAT" ("ID") ENABLE;

  ALTER TABLE "BR_FERIEPENGER_PR_AAR" ADD CONSTRAINT "FK_BR_FERIEPENGER_PR_AAR_1" FOREIGN KEY ("BR_FERIEPENGER_ID")
	  REFERENCES "BR_FERIEPENGER" ("ID") ENABLE;
  ALTER TABLE "BR_FERIEPENGER_PR_AAR" ADD CONSTRAINT "FK_BR_FERIEPENGER_PR_AAR_2" FOREIGN KEY ("BEREGNINGSRESULTAT_ANDEL_ID")
	  REFERENCES "BR_ANDEL" ("ID") ENABLE;

  ALTER TABLE "TOTRINNRESULTATGRUNNLAG" ADD CONSTRAINT "FK_TOTRINNRESULTATGRUNNLAG_1" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;
  ALTER TABLE "TOTRINNRESULTATGRUNNLAG" ADD CONSTRAINT "FK_TOTRINNRESULTATGRUNNLAG_3" FOREIGN KEY ("YTELSES_FORDELING_GRUNNLAG_ID")
	  REFERENCES "GR_YTELSES_FORDELING" ("ID") ENABLE;
  ALTER TABLE "TOTRINNRESULTATGRUNNLAG" ADD CONSTRAINT "FK_TOTRINNRESULTATGRUNNLAG_4" FOREIGN KEY ("UTTAK_RESULTAT_ID")
	  REFERENCES "UTTAK_RESULTAT" ("ID") ENABLE;
  ALTER TABLE "TOTRINNRESULTATGRUNNLAG" ADD CONSTRAINT "FK_TOTRINNRESULTATGRUNNLAG_5" FOREIGN KEY ("BEREGNINGSGRUNNLAG_ID")
	  REFERENCES "BEREGNINGSGRUNNLAG" ("ID") ENABLE;

  ALTER TABLE "MEDLEMSKAP_VURDERING_LOPENDE" ADD CONSTRAINT "FK_VURDERT_MEDLEMSKAP_P_1" FOREIGN KEY ("VURDERT_PERIODE_ID")
	  REFERENCES "MEDLEMSKAP_VURDERING_PERIODE" ("ID") ENABLE;

  ALTER TABLE "TILBAKEKREVING_VALG" ADD CONSTRAINT "FK_TILBAKEKREVING_VALG_1" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;

  ALTER TABLE "BEHANDLING_OVERLAPP_INFOTRYGD" ADD CONSTRAINT "FK_BEH_OVERLAPP_INFOTRYGD_1" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;

  ALTER TABLE "BG_ARBEIDSTAKER_ANDEL" ADD CONSTRAINT "FK_BG_ARBEIDSTAKER_ANDEL" FOREIGN KEY ("BG_PR_STATUS_ANDEL_ID")
	  REFERENCES "BG_PR_STATUS_OG_ANDEL" ("ID") ENABLE;

  ALTER TABLE "BG_FRILANS_ANDEL" ADD CONSTRAINT "FK_BG_FRILANS_ANDEL" FOREIGN KEY ("BG_PR_STATUS_ANDEL_ID")
	  REFERENCES "BG_PR_STATUS_OG_ANDEL" ("ID") ENABLE;

  ALTER TABLE "BG_AKTIVITET" ADD CONSTRAINT "FK_BG_AKTIVITET_01" FOREIGN KEY ("BG_AKTIVITETER_ID")
	  REFERENCES "BG_AKTIVITETER" ("ID") ENABLE;

  ALTER TABLE "ETTERKONTROLL" ADD CONSTRAINT "FK_ETTERKONTROLL_1" FOREIGN KEY ("FAGSAK_ID")
	  REFERENCES "FAGSAK" ("ID") ENABLE;

  ALTER TABLE "RISIKOKLASSIFISERING" ADD CONSTRAINT "FK_RISIKOKLASSIFISERING_1" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;

  ALTER TABLE "TILBAKEKREVING_INNTREKK" ADD CONSTRAINT "FK_TILBAKEKREVING_INNTREKK_1" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;

  ALTER TABLE "OKO_OMPOSTERING_116" ADD CONSTRAINT "FK_OKO_OMPOSTERING_116_1" FOREIGN KEY ("OKO_OPPDRAG_110_ID")
	  REFERENCES "OKO_OPPDRAG_110" ("ID") ENABLE;

  ALTER TABLE "SVP_TILRETTELEGGING" ADD CONSTRAINT "FK_SVP_TILRETTELEGGING_2" FOREIGN KEY ("SVP_TILRETTELEGGINGER_ID")
	  REFERENCES "SVP_TILRETTELEGGINGER" ("ID") ENABLE;

  ALTER TABLE "SVP_GRUNNLAG" ADD CONSTRAINT "FK_SVP_GRUNNLAG_1" FOREIGN KEY ("OPPRINNELINGE_TRLG_ID")
	  REFERENCES "SVP_TILRETTELEGGINGER" ("ID") ENABLE;
  ALTER TABLE "SVP_GRUNNLAG" ADD CONSTRAINT "FK_SVP_GRUNNLAG_2" FOREIGN KEY ("OVERSTYRTE_TRLG_ID")
	  REFERENCES "SVP_TILRETTELEGGINGER" ("ID") ENABLE;

  ALTER TABLE "SVP_UTTAK_RESULTAT" ADD CONSTRAINT "FK_SVP_UTTAK_RESULTAT_1" FOREIGN KEY ("BEHANDLING_RESULTAT_ID")
	  REFERENCES "BEHANDLING_RESULTAT" ("ID") ENABLE;

  ALTER TABLE "SVP_UTTAK_ARBEIDSFORHOLD" ADD CONSTRAINT "FK_SVP_UTTAK_ARBEIDSFORHOLD_1" FOREIGN KEY ("SVP_UTTAK_RESULTAT_ID")
	  REFERENCES "SVP_UTTAK_RESULTAT" ("ID") ENABLE;

  ALTER TABLE "SVP_UTTAK_PERIODE" ADD CONSTRAINT "FK_SVP_UTTAK_PERIODE_1" FOREIGN KEY ("SVP_UTTAK_ARBEIDSFORHOLD_ID")
	  REFERENCES "SVP_UTTAK_ARBEIDSFORHOLD" ("ID") ENABLE;

  ALTER TABLE "BG_AKTIVITET_OVERSTYRING" ADD CONSTRAINT "FK_BA_OVERSTYRINGER_01" FOREIGN KEY ("BA_OVERSTYRINGER_ID")
	  REFERENCES "BG_AKTIVITET_OVERSTYRINGER" ("ID") ENABLE;

  ALTER TABLE "ANKE_RESULTAT" ADD CONSTRAINT "FK_ANKE_RESULTAT_1" FOREIGN KEY ("ANKE_BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;
  ALTER TABLE "ANKE_RESULTAT" ADD CONSTRAINT "FK_ANKE_RESULTAT_2" FOREIGN KEY ("PAA_ANKET_BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;

  ALTER TABLE "ANKE_VURDERING_RESULTAT" ADD CONSTRAINT "FK_ANKE_VURDERING_RESULTAT_1" FOREIGN KEY ("ANKE_RESULTAT_ID")
	  REFERENCES "ANKE_RESULTAT" ("ID") ENABLE;

  ALTER TABLE "BG_REFUSJON_OVERSTYRING" ADD CONSTRAINT "FK_BR_OVERSTYRINGER_01" FOREIGN KEY ("BR_OVERSTYRINGER_ID")
	  REFERENCES "BG_REFUSJON_OVERSTYRINGER" ("ID") ENABLE;

  ALTER TABLE "BG_REGEL_SPORING" ADD CONSTRAINT "FK_BG_REGEL_SPORING_01" FOREIGN KEY ("BG_ID")
	  REFERENCES "BEREGNINGSGRUNNLAG" ("ID") ENABLE;

  ALTER TABLE "ABAKUS_INNHENTING_LOGG" ADD CONSTRAINT "FK_ABAKUS_INN_LOGG_01" FOREIGN KEY ("BEHANDLING_ID")
	  REFERENCES "BEHANDLING" ("ID") ENABLE;

  ALTER TABLE "BG_SG_PR_STATUS" ADD CONSTRAINT "FK_BG_SG_PR_STATUS_01" FOREIGN KEY ("BEREGNINGSGRUNNLAG_ID")
	  REFERENCES "BEREGNINGSGRUNNLAG" ("ID") ENABLE;

  ALTER TABLE "PROSESS_TASK" ADD CONSTRAINT "FK_PROSESS_TASK_1" FOREIGN KEY ("TASK_TYPE")
	  REFERENCES "PROSESS_TASK_TYPE" ("KODE") ENABLE;
	  
	  
-- INDEX

  CREATE UNIQUE INDEX "UIDX_BEHANDLING_03" ON "BEHANDLING" ("UUID") ;

  CREATE UNIQUE INDEX "UIDX_FAGSAK_1" ON "FAGSAK" ("SAKSNUMMER") ;

  -- CREATE UNIQUE INDEX "UIDX_KODELISTE_1" ON "KODELISTE" ("KODE", "KODEVERK");

  CREATE INDEX "UIDX_UIDENTIFISERT_BARN_2" ON "FH_UIDENTIFISERT_BARN" ("FAMILIE_HENDELSE_ID") ;

  CREATE UNIQUE INDEX "UIDX_FAGSAK_PROSESS_TASK_1" ON "FAGSAK_PROSESS_TASK" ("FAGSAK_ID", "PROSESS_TASK_ID") ;

  CREATE UNIQUE INDEX "UIDX_HISTORIKKINNSLAG_01" ON "HISTORIKKINNSLAG" ("UUID") ;

  CREATE UNIQUE INDEX "UIDX_BEHANDLING_VEDTAK_1" ON "BEHANDLING_VEDTAK" ("BEHANDLING_RESULTAT_ID") ;

  CREATE UNIQUE INDEX "UIDX_OPPTJENING_AKTIVITET_01" ON "OPPTJENING_AKTIVITET" ("OPPTJENINGSPERIODE_ID", "FOM", "AKTIVITET_TYPE", "AKTIVITET_REFERANSE", "REFERANSE_TYPE") ;

  CREATE UNIQUE INDEX "UIDX_UIDENTIFISERT_BARN_1" ON "FH_UIDENTIFISERT_BARN" ("FAMILIE_HENDELSE_ID", "BARN_NUMMER") ;

  CREATE INDEX "UIDX_OPPTJENING_AKTIVITET_04" ON "OPPTJENING_AKTIVITET" ("FOM", "TOM", "AKTIVITET_TYPE", "OPPTJENINGSPERIODE_ID") ;

  CREATE UNIQUE INDEX "UIDX_ABAKUS_INNHENTING_LOGG_01" ON "ABAKUS_INNHENTING_LOGG" (CASE  WHEN "AKTIV"='J' THEN "BEHANDLING_ID" ELSE NULL END , CASE  WHEN "AKTIV"='J' THEN "AKTIV" ELSE NULL END ) ;

  CREATE UNIQUE INDEX "UIDX_GR_FAMILIE_HENDELSE_01" ON "GR_FAMILIE_HENDELSE" (CASE "AKTIV" WHEN 'J' THEN "BEHANDLING_ID" ELSE NULL END , CASE "AKTIV" WHEN 'J' THEN "AKTIV" ELSE NULL END ) ;

  CREATE UNIQUE INDEX "UIDX_KODE_SPRAK" ON "KODELISTE_NAVN_I18N" ("KL_KODEVERK", "KL_KODE", "SPRAK") ;

  CREATE UNIQUE INDEX "UIDX_GR_SOEKNAD_01" ON "GR_SOEKNAD" (CASE "AKTIV" WHEN 'J' THEN "BEHANDLING_ID" ELSE NULL END , CASE "AKTIV" WHEN 'J' THEN "AKTIV" ELSE NULL END ) ;

  CREATE UNIQUE INDEX "UIDX_MEDLEMSKAP_VL_1" ON "MEDLEMSKAP_VURDERING_LOPENDE" ("VURDERINGSDATO", "VURDERT_PERIODE_ID") ;

  CREATE UNIQUE INDEX "UIDX_ANDELSNR" ON "BG_PR_STATUS_OG_ANDEL" ("BG_PERIODE_ID", "ANDELSNR") ;

  CREATE UNIQUE INDEX "UIDX_BRUKER_1" ON "BRUKER" ("AKTOER_ID") ;

  CREATE UNIQUE INDEX "UIDX_INNSYN_01" ON "INNSYN" ("BEHANDLING_ID") ;

-- Baseline for INDEX er ferdig!!
