DELETE FROM KODELISTE_NAVN_I18N
WHERE KL_KODEVERK = 'DOKUMENT_TYPE_ID' and KL_KODE='I000116';
DELETE FROM KODELISTE
WHERE KODEVERK = 'DOKUMENT_TYPE_ID' and KODE='I000116';

DELETE FROM KODELISTE_NAVN_I18N
WHERE KL_KODEVERK = 'DOKUMENT_TYPE_ID' and KL_KODE='I000117';
DELETE FROM KODELISTE
WHERE KODEVERK = 'DOKUMENT_TYPE_ID' and KODE='I000117';

INSERT INTO KODELISTE (KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES ('DOKUMENT_TYPE_ID','DOK_HV','I000116','Bekreftelse på øvelse eller tjeneste i Forsvaret eller Sivilforsvaret',
        to_date('01/01/2000', 'dd/mm/rrrr'),to_date('31/12/9999', 'dd/mm/rrrr'));
INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN)
VALUES (SEQ_KODELISTE_NAVN_I18N.nextval,'DOKUMENT_TYPE_ID','DOK_HV','NB','Bekreftelse på øvelse eller tjeneste i Forsvaret eller Sivilforsvaret');

INSERT INTO KODELISTE (KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES ('DOKUMENT_TYPE_ID','DOK_NAV_TILTAK','I000117','Bekreftelse på tiltak i regi av Arbeids- og velferdsetaten',
        to_date('01/01/2000', 'dd/mm/rrrr'),to_date('31/12/9999', 'dd/mm/rrrr'));
INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN)
VALUES (SEQ_KODELISTE_NAVN_I18N.nextval,'DOKUMENT_TYPE_ID','DOK_NAV_TILTAK','NB','Bekreftelse på tiltak i regi av Arbeids- og velferdsetaten');
