ALTER TABLE OKO_OPPDRAG_110 set unused (VERSJON);
ALTER TABLE OKO_OPPDRAG_110 set unused (ENDRET_AV);
ALTER TABLE OKO_OPPDRAG_110 set unused (ENDRET_TID);
ALTER TABLE OKO_OPPDRAG_110 set unused (KODE_AKSJON);
ALTER TABLE OKO_OPPDRAG_110 set unused (UTBET_FREKVENS);
ALTER TABLE OKO_OPPDRAG_110 set unused (DATO_OPPDRAG_GJELDER_FOM);
