CREATE SEQUENCE SEQ_GR_PLEIEPENGER  MINVALUE 1 INCREMENT BY 50 START WITH 1 NOCACHE  NOCYCLE ;
CREATE SEQUENCE SEQ_PSB_PERIODER  MINVALUE 1 INCREMENT BY 50 START WITH 1 NOCACHE  NOCYCLE ;
CREATE SEQUENCE SEQ_PSB_INNLAGT_PERIODE  MINVALUE 1 INCREMENT BY 50 START WITH 1 NOCACHE  NOCYCLE ;

CREATE TABLE GR_PLEIEPENGER (
    id NUMBER(19,0) NOT NULL,
	behandling_id NUMBER(19,0) NOT NULL,
    psb_perioder_id NUMBER(19,0),
	opprettet_av VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
	opprettet_tid TIMESTAMP (3) DEFAULT systimestamp NOT NULL,
	endret_av VARCHAR2(20 CHAR),
	endret_tid TIMESTAMP (3),
	aktiv VARCHAR2(1 CHAR) DEFAULT 'J' NOT NULL
   );

CREATE TABLE PSB_PERIODER (
    ID NUMBER(19,0) NOT NULL,
    OPPRETTET_AV VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
    OPPRETTET_TID TIMESTAMP (3) DEFAULT systimestamp NOT NULL,
    ENDRET_AV VARCHAR2(20 CHAR),
    ENDRET_TID TIMESTAMP (3)
) ;


ALTER TABLE GR_PLEIEPENGER ADD CONSTRAINT PK_GR_PLEIEPENGER PRIMARY KEY (id) USING INDEX;
ALTER TABLE GR_PLEIEPENGER ADD CONSTRAINT FK_GR_PLEIEPENGER_1 FOREIGN KEY (behandling_id) REFERENCES BEHANDLING(id);
ALTER TABLE GR_PLEIEPENGER ADD CONSTRAINT FK_GR_PLEIEPENGER_2 FOREIGN KEY (psb_perioder_id) REFERENCES PSB_PERIODER(id);
ALTER TABLE GR_PLEIEPENGER ADD CONSTRAINT GR_PLEIEPENGER_AKTIV CHECK (aktiv IN ('J', 'N'));

CREATE INDEX IDX_GR_PLEIEPENGER_1 ON GR_PLEIEPENGER (BEHANDLING_ID);
CREATE INDEX IDX_GR_PLEIEPENGER_2 ON GR_PLEIEPENGER (psb_perioder_id);

COMMENT ON COLUMN GR_PLEIEPENGER.id IS 'PK';
COMMENT ON COLUMN GR_PLEIEPENGER.behandling_id IS 'Foreign key til behandling';
COMMENT ON COLUMN GR_PLEIEPENGER.psb_perioder_id IS 'Foreign key til psb_perioder';
COMMENT ON COLUMN GR_PLEIEPENGER.aktiv IS 'Om valg er aktivt';
COMMENT ON TABLE GR_PLEIEPENGER IS 'Behandlingsgrunnlag for Pleiepenger med innleggelse';

ALTER TABLE PSB_PERIODER ADD CONSTRAINT PK_PSB_PERIODER PRIMARY KEY (ID) USING INDEX ;
COMMENT ON COLUMN PSB_PERIODER.ID IS 'Primærnøkkel';
COMMENT ON TABLE PSB_PERIODER  IS 'Aggregering av informasjon om pleiepenger';

create table PSB_INNLAGT_PERIODE
(
    ID NUMBER(19,0) not null,
    FOM DATE not null,
    TOM DATE not null,
    PLEIETRENGENDE_AKTOER_ID VARCHAR2(100 char) not null,
    PSB_SAKSNUMMER VARCHAR2(100 char),
    PSB_PERIODER_ID NUMBER(19) not null
        constraint FK_PSB_INNLAGT_PERIODE references PSB_PERIODER,
    OPPRETTET_AV VARCHAR2(20 char) default 'VL' not null,
    OPPRETTET_TID TIMESTAMP(3) default systimestamp not null,
    ENDRET_AV VARCHAR2(20 char),
    ENDRET_TID TIMESTAMP(3)

);
ALTER TABLE PSB_INNLAGT_PERIODE ADD CONSTRAINT PK_PSB_INNLAGT_PERIODE PRIMARY KEY (ID) USING INDEX ;
ALTER TABLE PSB_INNLAGT_PERIODE ADD CONSTRAINT FK_PSB_INNLAGT_PERIODE1 FOREIGN KEY (PSB_PERIODER_ID) REFERENCES PSB_PERIODER(id);

comment on table PSB_INNLAGT_PERIODE is 'Pleiepenger - periode med innleggelse';
comment on column PSB_INNLAGT_PERIODE.ID is 'Primærnøkkel';
comment on column PSB_INNLAGT_PERIODE.FOM is 'Innlagt fom';
comment on column PSB_INNLAGT_PERIODE.TOM is 'Innlagt tom';
comment on column PSB_INNLAGT_PERIODE.PSB_PERIODER_ID is 'FK: mot aggregat';
comment on column PSB_INNLAGT_PERIODE.PLEIETRENGENDE_AKTOER_ID is 'Aktørid fra VLBS';
comment on column PSB_INNLAGT_PERIODE.PSB_SAKSNUMMER is 'Saksnummer fra VLBS';

create index IDX_PSB_INNLAGT_PERIODE_1 on PSB_INNLAGT_PERIODE (PSB_PERIODER_ID);

