ALTER TABLE OKO_OMPOSTERING_116 set unused (ENDRET_AV);
ALTER TABLE OKO_OMPOSTERING_116 set unused (ENDRET_TID);
ALTER TABLE OKO_OMPOSTERING_116 set unused (SAKSBEH_ID);

ALTER TABLE OPPDRAG_KVITTERING set unused (ENDRET_AV);
ALTER TABLE OPPDRAG_KVITTERING set unused (ENDRET_TID);
ALTER TABLE OPPDRAG_KVITTERING set unused (VERSJON);

ALTER TABLE OKO_REFUSJONSINFO_156 set unused (ENDRET_AV);
ALTER TABLE OKO_REFUSJONSINFO_156 set unused (ENDRET_TID);
ALTER TABLE OKO_REFUSJONSINFO_156 set unused (VERSJON);


