ALTER TABLE BEHANDLING_DOKUMENT_BESTILT add BESTILLING_UUID RAW(16);
ALTER TABLE BEHANDLING_DOKUMENT_BESTILT add JOURNALPOST_ID VARCHAR2(20 CHAR);
COMMENT ON COLUMN BEHANDLING_DOKUMENT_BESTILT.BESTILLING_UUID IS 'Referanse til dokumentbestilling';
COMMENT ON COLUMN BEHANDLING_DOKUMENT_BESTILT.JOURNALPOST_ID IS 'JournalpostId for produsert dokument';

CREATE INDEX IDX_BEH_DOK_BESTILL_UUID ON BEHANDLING_DOKUMENT_BESTILT (BESTILLING_UUID);
