ALTER TABLE BEREGNINGSGRUNNLAG_PERIODE SET UNUSED (regel_evaluering);
ALTER TABLE BEREGNINGSGRUNNLAG_PERIODE SET UNUSED (regel_evaluering_fastsett);
ALTER TABLE BEREGNINGSGRUNNLAG_PERIODE SET UNUSED (regel_input);
ALTER TABLE BEREGNINGSGRUNNLAG_PERIODE SET UNUSED (regel_input_fastsett);
ALTER TABLE BEREGNINGSGRUNNLAG_PERIODE SET UNUSED (regel_input_fastsett_2);
ALTER TABLE BEREGNINGSGRUNNLAG_PERIODE SET UNUSED (regel_evaluering_fastsett_2);
ALTER TABLE BEREGNINGSGRUNNLAG_PERIODE SET UNUSED (regel_input_vilkar);
ALTER TABLE BEREGNINGSGRUNNLAG_PERIODE SET UNUSED (regel_evaluering_vilkar);
ALTER TABLE BEREGNINGSGRUNNLAG_PERIODE SET UNUSED (regel_input_oppdater_svp);
ALTER TABLE BEREGNINGSGRUNNLAG_PERIODE SET UNUSED (regel_evaluering_oppdater_svp);

ALTER TABLE BEREGNINGSGRUNNLAG SET UNUSED (regellogg_skjaringstidspunkt);
ALTER TABLE BEREGNINGSGRUNNLAG SET UNUSED (regellogg_brukers_status);
ALTER TABLE BEREGNINGSGRUNNLAG SET UNUSED (regelinput_skjaringstidspunkt);
ALTER TABLE BEREGNINGSGRUNNLAG SET UNUSED (regelinput_brukers_status);
ALTER TABLE BEREGNINGSGRUNNLAG SET UNUSED (regelinput_periodisering);
