ALTER TABLE BG_PR_STATUS_OG_ANDEL
ADD KILDE VARCHAR2(100 CHAR) DEFAULT 'PROSESS_START';

comment on column BG_PR_STATUS_OG_ANDEL.KILDE IS 'Angir kilde/opphav for andel';


UPDATE BG_PR_STATUS_OG_ANDEL
SET KILDE = 'PROSESS_START';

ALTER TABLE BG_PR_STATUS_OG_ANDEL
MODIFY (KILDE NOT NULL);
