ALTER TABLE YF_FORDELING_PERIODE SET UNUSED (MOTTATT_DATO_TEMP);
ALTER TABLE UTTAK_RESULTAT_PERIODE_SOKNAD SET UNUSED (MOTTATT_DATO_2);
ALTER TABLE UTTAK_RESULTAT_PERIODE_SOKNAD SET UNUSED (MOTTATT_DATO_3);
