ALTER TABLE OKO_OPPDRAG_110 ADD "NOKKEL_AVSTEMMING" VARCHAR2(30 CHAR);
COMMENT ON COLUMN "OKO_OPPDRAG_110"."NOKKEL_AVSTEMMING" IS 'Brukes til å identifisere data som skal avstemmes og er lik tidspunktet meldingen ble sendt ut.';
CREATE INDEX "IDX_OKO_OPPDRAG_110_2" ON "OKO_OPPDRAG_110" ("NOKKEL_AVSTEMMING");
