ALTER TABLE BR_RESULTAT_BEHANDLING ADD CONSTRAINT FK_BR_RESULTAT_BEHANDLING_2 FOREIGN KEY (BG_BEREGNINGSRESULTAT_FP_ID)
REFERENCES BR_BEREGNINGSRESULTAT (ID);

CREATE INDEX IDX_BG_BEREGNINGSRESULTAT_FP_ID ON BR_RESULTAT_BEHANDLING (BG_BEREGNINGSRESULTAT_FP_ID);

ALTER TABLE BR_RESULTAT_BEHANDLING ADD CONSTRAINT FK_BR_RESULTAT_BEHANDLING_3 FOREIGN KEY (UTBET_BEREGNINGSRESULTAT_FP_ID)
REFERENCES BR_BEREGNINGSRESULTAT (ID);

CREATE INDEX IDX_UTBET_BEREGNINGSRESULTAT_FP_ID ON BR_RESULTAT_BEHANDLING (UTBET_BEREGNINGSRESULTAT_FP_ID);
