ALTER TABLE VERGE DROP COLUMN ENDRET_AV;
ALTER TABLE VERGE DROP COLUMN ENDRET_TID;

ALTER TABLE VERGE_ORGANISASJON DROP COLUMN ENDRET_AV;
ALTER TABLE VERGE_ORGANISASJON DROP COLUMN ENDRET_TID;

ALTER TABLE HISTORIKKINNSLAG DROP COLUMN UUID;
ALTER TABLE HISTORIKKINNSLAG DROP COLUMN HISTORIKK_TID;
ALTER TABLE HISTORIKKINNSLAG DROP COLUMN OPPRETTET_I_SYSTEM;
