ALTER TABLE OKO_OPPDRAG_LINJE_150 set unused (FRADRAG_TILLEGG);
ALTER TABLE OKO_OPPDRAG_LINJE_150 set unused (BRUK_KJORE_PLAN);
ALTER TABLE OKO_OPPDRAG_LINJE_150 set unused (SAKSBEH_ID);
ALTER TABLE OKO_OPPDRAG_LINJE_150 set unused (HENVISNING);
ALTER TABLE OKO_OPPDRAG_LINJE_150 set unused (VERSJON);
ALTER TABLE OKO_OPPDRAG_LINJE_150 set unused (ENDRET_AV);
ALTER TABLE OKO_OPPDRAG_LINJE_150 set unused (ENDRET_TID);
