CREATE TABLE GR_OPPTJ_UTLAND_DOK_VALG(
    id NUMBER(19,0) NOT NULL,
	behandling_id NUMBER(19,0) NOT NULL,
	versjon NUMBER(19,0) DEFAULT 0 NOT NULL,
	opprettet_av VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
	opprettet_tid TIMESTAMP (3) DEFAULT systimestamp NOT NULL,
	endret_av VARCHAR2(20 CHAR),
	endret_tid TIMESTAMP (3),
	aktiv VARCHAR2(1 CHAR) DEFAULT 'J' NOT NULL,
	dok_status VARCHAR(40 CHAR) NOT NULL
   );

ALTER TABLE GR_OPPTJ_UTLAND_DOK_VALG ADD CONSTRAINT PK_GR_OPPTJ_UTLAND_DOK_VALG PRIMARY KEY (id);
ALTER TABLE GR_OPPTJ_UTLAND_DOK_VALG ADD CONSTRAINT FK_GR_OPPTJ_UTLAND_DOK_VALG_1 FOREIGN KEY (behandling_id) REFERENCES BEHANDLING(id);
ALTER TABLE GR_OPPTJ_UTLAND_DOK_VALG ADD CONSTRAINT GR_OPPTJ_UTLAND_DOK_VALG_AKTIV CHECK (aktiv IN ('J', 'N'));

CREATE INDEX IDX_GR_OPPTJ_UTLAND_DOK_VALG_1 ON GR_OPPTJ_UTLAND_DOK_VALG (BEHANDLING_ID);
CREATE SEQUENCE SEQ_GR_OPPTJ_UTLAND_DOK_VALG INCREMENT BY 50;

COMMENT ON COLUMN GR_OPPTJ_UTLAND_DOK_VALG.id IS 'PK';
COMMENT ON COLUMN GR_OPPTJ_UTLAND_DOK_VALG.behandling_id IS 'Foreign key til behandling';
COMMENT ON COLUMN GR_OPPTJ_UTLAND_DOK_VALG.dok_status IS 'Saksbehandlers valg om dokumentasjon skal hentes eller ikke';
COMMENT ON COLUMN GR_OPPTJ_UTLAND_DOK_VALG.versjon IS 'Angir versjon for optimistisk låsing';
COMMENT ON COLUMN GR_OPPTJ_UTLAND_DOK_VALG.aktiv IS 'Om valg er aktivt';

COMMENT ON TABLE GR_OPPTJ_UTLAND_DOK_VALG IS 'Lagrer saksbehandlers valg om dokumentasjon fra utlandet skal innhentes';
