update ANKE_VURDERING_RESULTAT_DVH set TR_VURDERING = '-' where TR_VURDERING is null;
update ANKE_VURDERING_RESULTAT_DVH set TR_VURDERING_OMGJOER = '-' where TR_VURDERING_OMGJOER is null;
update ANKE_VURDERING_RESULTAT_DVH set TR_OMGJOER_AARSAK = '-' where TR_OMGJOER_AARSAK is null;
