-- behandlingMetode og papir
alter table BEHANDLING_DVH ADD PAPIR_SOKNAD VARCHAR2(1 CHAR);
COMMENT ON COLUMN BEHANDLING_DVH.PAPIR_SOKNAD IS 'Flagg for behandling: 1-papir,0-digital';
alter table BEHANDLING_DVH ADD BEHANDLING_METODE VARCHAR2(100 CHAR);
COMMENT ON COLUMN BEHANDLING_DVH.BEHANDLING_METODE IS 'Utledet behandlingsmetode';
alter table BEHANDLING_DVH ADD REVURDERING_AARSAK VARCHAR2(100 CHAR);
COMMENT ON COLUMN BEHANDLING_DVH.REVURDERING_AARSAK IS 'Hovedårsak for revurdering';

-- behandlingsrelaterte tidspunkt
alter table BEHANDLING_DVH ADD MOTTATT_TID TIMESTAMP(3);
COMMENT ON COLUMN BEHANDLING_DVH.MOTTATT_TID IS 'Søknad eller klage mottatt';
alter table BEHANDLING_DVH ADD REGISTRERT_TID TIMESTAMP(3);
COMMENT ON COLUMN BEHANDLING_DVH.REGISTRERT_TID IS 'Behandling registrert';
alter table BEHANDLING_DVH ADD KAN_BEHANDLES_TID TIMESTAMP(3);
COMMENT ON COLUMN BEHANDLING_DVH.KAN_BEHANDLES_TID IS 'Behandling kan ikke begynne før';
alter table BEHANDLING_DVH ADD FERDIG_BEHANDLET_TID TIMESTAMP(3);
COMMENT ON COLUMN BEHANDLING_DVH.FERDIG_BEHANDLET_TID IS 'Behandling avsluttet';
alter table BEHANDLING_DVH ADD FORVENTET_OPPSTART_TID DATE;
COMMENT ON COLUMN BEHANDLING_DVH.FORVENTET_OPPSTART_TID IS 'Første uttaksdato fra søknad';

-- vedtaksrelaterte tidspunkt
ALTER TABLE BEHANDLING_VEDTAK_DVH ADD VEDTAK_TID TIMESTAMP(3);
comment on column BEHANDLING_VEDTAK_DVH.VEDTAK_TID IS 'Tidspunkt da vedtak ble fattet';
ALTER TABLE BEHANDLING_VEDTAK_DVH ADD UTBETALT_TID DATE;
comment on column BEHANDLING_VEDTAK_DVH.UTBETALT_TID IS 'Dato for første utbetaling';
