DROP TABLE AKSJONSPUNKT_DEF_DVH ;
DROP TABLE KONTROLL_DVH ;
DROP TABLE FAGSAK_RELASJON_DVH ;
DROP TABLE AKSJONSPUNKT_DVH;
DROP TABLE BEHANDLING_STEG_DVH ;
DROP TABLE BEHANDLING_VEDTAK_DVH ;
DROP TABLE FAGSAK_DVH ;

DROP SEQUENCE SEQ_AKSJONSPUNKT_DVH ;
DROP SEQUENCE SEQ_BEHANDLING_STEG_DVH ;
DROP SEQUENCE SEQ_BEHANDLING_VEDTAK_DVH ;
DROP SEQUENCE SEQ_FAGSAK_DVH ;
DROP SEQUENCE SEQ_FAGSAK_RELASJON_DVH ;

ALTER TABLE BEHANDLING_DVH
    SET UNUSED (OPPRETTET_DATO, VEDTAK_ID, TOTRINNSBEHANDLING, FERDIG, VEDTATT, AVBRUTT, MOTTATT_TIDSPUNKT,
                SOEKNAD_FAMILIE_HENDELSE, BEKREFTET_FAMILIE_HENDELSE, OVERSTYRT_FAMILIE_HENDELSE);
