CREATE TABLE FAGSAK_RELASJON_DVH
  (
  TRANS_ID           NUMBER(19)         NOT NULL,
  TRANS_TID          TIMESTAMP(3)       NOT NULL,
  FAGSAK_EN_ID       NUMBER(19)         NOT NULL,
  FAGSAK_TO_ID       NUMBER(19),
  FUNKSJONELL_TID    TIMESTAMP(3)       NOT NULL,
  dekningsgrad       NUMBER(3)          NOT NULL,
  AVSLUTTNINGSDATO   DATE ,
  ENDRET_AV          VARCHAR2(20 CHAR)
  ) ;
ALTER TABLE FAGSAK_RELASJON_DVH ADD CONSTRAINT PK_FAGSAK_RELASJON_DVH PRIMARY KEY ( TRANS_ID ) ;
CREATE SEQUENCE SEQ_FAGSAK_RELASJON_DVH MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
GRANT SELECT on SEQ_FAGSAK_RELASJON_DVH to FPSAK_HIST_SKRIVE_ROLE;

GRANT ALL ON FAGSAK_RELASJON_DVH TO FPSAK_HIST_SKRIVE_ROLE;

COMMENT ON TABLE FAGSAK_RELASJON_DVH  IS 'En transaksjonstabell med alle endringer på fagsakrelasjonen.';
COMMENT ON COLUMN FAGSAK_RELASJON_DVH.TRANS_ID IS 'Primær nøkkel for fagsakrelesjon transaksjoner';
COMMENT ON COLUMN FAGSAK_RELASJON_DVH.TRANS_TID IS 'Timestamp som forteller nå transaksjonen inntraff. ';
COMMENT ON COLUMN FAGSAK_RELASJON_DVH.FAGSAK_EN_ID IS 'Id til Fagsak 1';
COMMENT ON COLUMN FAGSAK_RELASJON_DVH.FAGSAK_TO_ID IS 'Id til Fagsak 2';
COMMENT ON COLUMN FAGSAK_RELASJON_DVH.dekningsgrad IS 'Dekningsgrad for foreldrepenger';
COMMENT ON COLUMN FAGSAK_RELASJON_DVH.AVSLUTTNINGSDATO IS 'Dato for når relasjonen avsluttet';
COMMENT ON COLUMN FAGSAK_RELASJON_DVH.ENDRET_AV IS 'Samme som opprettet_av eller endret_av i VL';
