DROP TABLE ANKE_VURDERING_RESULTAT_DVH ;
DROP TABLE KLAGE_VURDERING_RESULTAT_DVH ;
DROP TABLE KLAGE_FORMKRAV_DVH ;
DROP TABLE VEDTAK_UTBETALING_DVH;

DROP SEQUENCE SEQ_ANKE_VURDERING_RES_DVH ;
DROP SEQUENCE SEQ_KLAGE_VURDERING_RES_DVH ;
DROP SEQUENCE SEQ_KLAGE_FORMKRAV_DVH ;
DROP SEQUENCE SEQ_VEDTAK_UTBETALING_DVH ;
