-- skal flyttes fra behandling_vedtak_dvh
ALTER TABLE BEHANDLING_DVH ADD VILKAR_IKKE_OPPFYLT VARCHAR2(100 CHAR);
comment on column BEHANDLING_DVH.VILKAR_IKKE_OPPFYLT IS 'Vilkår som ikke er oppfylt';
ALTER TABLE BEHANDLING_DVH ADD VEDTAK_RESULTAT_TYPE VARCHAR2(100 CHAR);
comment on column BEHANDLING_DVH.VEDTAK_RESULTAT_TYPE IS 'Vedtaksresultat';
ALTER TABLE BEHANDLING_DVH ADD VEDTAK_TID TIMESTAMP(3);
comment on column BEHANDLING_DVH.VEDTAK_TID IS 'Tidspunkt da vedtak ble fattet';
ALTER TABLE BEHANDLING_DVH ADD UTBETALT_TID DATE;
comment on column BEHANDLING_DVH.UTBETALT_TID IS 'Dato for første utbetaling';
-- skal forenkles til ett felt
ALTER TABLE BEHANDLING_DVH ADD FAMILIE_HENDELSE_TYPE VARCHAR2(100 CHAR);
comment on column BEHANDLING_DVH.FAMILIE_HENDELSE_TYPE IS 'Omstendighetene som saken gjelder';
