ALTER TABLE BEHANDLING_DVH ADD SAKSNUMMER VARCHAR2(100 CHAR);
comment on column BEHANDLING_DVH.SAKSNUMMER IS 'Saksnummer behandlingen tilhører';
ALTER TABLE BEHANDLING_DVH ADD AKTOER_ID VARCHAR2(50 CHAR);
comment on column BEHANDLING_DVH.AKTOER_ID IS 'AktørId for bruker saken gjelder';
ALTER TABLE BEHANDLING_DVH ADD YTELSE_TYPE VARCHAR2(100 CHAR);
comment on column BEHANDLING_DVH.YTELSE_TYPE IS 'Ytelsen saken gjelder';
