ALTER TABLE BEHANDLING_DVH ADD SOEKNAD_FAMILIE_HENDELSE VARCHAR2(100 CHAR);
ALTER TABLE BEHANDLING_DVH ADD BEKREFTET_FAMILIE_HENDELSE VARCHAR2(100 CHAR);
ALTER TABLE BEHANDLING_DVH ADD OVERSTYRT_FAMILIE_HENDELSE VARCHAR2(100 CHAR);

