-- endringer anke for Trygderettsresultat
ALTER TABLE ANKE_VURDERING_RESULTAT_DVH ADD TR_VURDERING VARCHAR2(100 CHAR);
ALTER TABLE ANKE_VURDERING_RESULTAT_DVH ADD TR_VURDERING_OMGJOER VARCHAR2(100 CHAR);
ALTER TABLE ANKE_VURDERING_RESULTAT_DVH ADD TR_OMGJOER_AARSAK VARCHAR2(100 CHAR);
ALTER TABLE ANKE_VURDERING_RESULTAT_DVH ADD TR_KJENNELSE_DATO DATE;

comment on column ANKE_VURDERING_RESULTAT_DVH.TR_VURDERING IS 'Trygderettens vurdering';
comment on column ANKE_VURDERING_RESULTAT_DVH.TR_VURDERING_OMGJOER IS 'Trygderettens omgjøring';
comment on column ANKE_VURDERING_RESULTAT_DVH.TR_OMGJOER_AARSAK IS 'Trygderettens årsak til omgjøring';
comment on column ANKE_VURDERING_RESULTAT_DVH.TR_KJENNELSE_DATO IS 'Trygderettens kjennelse dato';
