ALTER TABLE BEHANDLING_DVH ADD RELATERT_TIL_UUID RAW(16);
COMMENT ON COLUMN BEHANDLING_DVH.RELATERT_TIL_UUID IS 'Relatert til behandling med UUID';

ALTER TABLE BEHANDLING_DVH ADD OMGJOERING_AARSAK VARCHAR2(100 CHAR);;
COMMENT ON COLUMN BEHANDLING_DVH.OMGJOERING_AARSAK IS 'Årsak til omgjøring av klage eller anke';
