CREATE TABLE KLAGE_FORMKRAV_DVH (
  TRANS_ID              NUMBER(19,0) NOT NULL,
  KLAGE_BEHANDLING_ID   NUMBER(19,0) NOT NULL,
  KLAGE_VURDERT_AV      VARCHAR2(100 CHAR) NOT NULL,
  GJELDER_VEDTAK        VARCHAR2(1 CHAR) NOT NULL,
  ER_KLAGER_PART        VARCHAR2(1 CHAR) NOT NULL,
  ER_FRIST_OVERHOLDT    VARCHAR2(1 CHAR) NOT NULL,
  ER_KONKRET            VARCHAR2(1 CHAR) NOT NULL,
  ER_SIGNERT            VARCHAR2(1 CHAR) NOT NULL,
  OPPRETTET_TID         TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  TRANS_TID             TIMESTAMP(3)       NOT NULL,
  FUNKSJONELL_TID       TIMESTAMP(3)       NOT NULL,
  ENDRET_AV             VARCHAR2(20 CHAR)
);
ALTER TABLE KLAGE_FORMKRAV_DVH ADD CONSTRAINT PK_KLAGE_FORMKRAV_DVH PRIMARY KEY ( TRANS_ID ) ;
CREATE SEQUENCE SEQ_KLAGE_FORMKRAV_DVH MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
GRANT SELECT on SEQ_KLAGE_FORMKRAV_DVH to FPSAK_HIST_SKRIVE_ROLE;
GRANT ALL ON KLAGE_FORMKRAV_DVH TO FPSAK_HIST_SKRIVE_ROLE;
CREATE INDEX IDX_KLAGE_FORMKRAV_DVH_1 on KLAGE_FORMKRAV_DVH(KLAGE_BEHANDLING_ID);

COMMENT ON COLUMN KLAGE_FORMKRAV_DVH.TRANS_ID IS 'Primærnøkkel';
COMMENT ON COLUMN KLAGE_FORMKRAV_DVH.KLAGE_BEHANDLING_ID IS 'referanse til klagebehandlingen';
COMMENT ON COLUMN KLAGE_FORMKRAV_DVH.KLAGE_VURDERT_AV IS 'Hvem som har vurdert klagen. np/nfp';
COMMENT ON COLUMN KLAGE_FORMKRAV_DVH.GJELDER_VEDTAK IS 'Vedtaket klagen gjelder for';
COMMENT ON COLUMN KLAGE_FORMKRAV_DVH.ER_KLAGER_PART IS 'Angir om klager er part i saken.';
COMMENT ON COLUMN KLAGE_FORMKRAV_DVH.ER_FRIST_OVERHOLDT IS 'Angir om frist er overholdt';
COMMENT ON COLUMN KLAGE_FORMKRAV_DVH.ER_KONKRET IS 'er konkret';
COMMENT ON COLUMN KLAGE_FORMKRAV_DVH.ER_SIGNERT IS 'er klagen signert';
COMMENT ON COLUMN KLAGE_FORMKRAV_DVH.OPPRETTET_TID IS 'Opprettettidspunkt.';
COMMENT ON COLUMN KLAGE_FORMKRAV_DVH.TRANS_TID IS 'Timestamp som forteller nå transaksjonen inntraff.';
COMMENT ON COLUMN KLAGE_FORMKRAV_DVH.FUNKSJONELL_TID IS 'Et tidsstempel når transaksjonen er funksjonelt gyldig fra.';
COMMENT ON COLUMN KLAGE_FORMKRAV_DVH.ENDRET_AV IS 'Opprettet_av eller endret_av i VL';


CREATE TABLE KLAGE_VURDERING_RESULTAT_DVH (
    TRANS_ID                              NUMBER(19,0) NOT NULL,
    KLAGE_BEHANDLING_ID                   NUMBER(19,0) NOT NULL,
    KLAGE_VURDERT_AV                      VARCHAR2(100) NOT NULL,
    KLAGEVURDERING                        VARCHAR2(100) NOT NULL,
    KLAGE_AVVIST_AARSAK                   VARCHAR2(100),
    KLAGE_MEDHOLD_AARSAK                  VARCHAR2(100),
    KLAGE_VURDERING_OMGJOER               VARCHAR2(100 char),
    VEDTAKSDATO_PAKLAGD_BEHANDLING        DATE,
    OPPRETTET_TID                         TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
    TRANS_TID                             TIMESTAMP(3)       NOT NULL,
    FUNKSJONELL_TID                       TIMESTAMP(3)       NOT NULL,
    ENDRET_AV                             VARCHAR2(20 CHAR)
);

ALTER TABLE KLAGE_VURDERING_RESULTAT_DVH ADD CONSTRAINT PK_KLAGE_VURDERING_RES_DVH PRIMARY KEY ( TRANS_ID ) ;
CREATE SEQUENCE SEQ_KLAGE_VURDERING_RES_DVH MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
GRANT SELECT on SEQ_KLAGE_VURDERING_RES_DVH to FPSAK_HIST_SKRIVE_ROLE;
GRANT ALL ON KLAGE_VURDERING_RESULTAT_DVH TO FPSAK_HIST_SKRIVE_ROLE;
CREATE INDEX IDX_KLAGE_VURDERING_RES_DVH_1 on KLAGE_VURDERING_RESULTAT_DVH(KLAGE_BEHANDLING_ID);


COMMENT ON COLUMN KLAGE_VURDERING_RESULTAT_DVH.TRANS_ID IS 'Primærnøkkel';
COMMENT ON COLUMN KLAGE_VURDERING_RESULTAT_DVH.KLAGE_BEHANDLING_ID IS 'referanse til klagebehandlingen';
COMMENT ON COLUMN KLAGE_VURDERING_RESULTAT_DVH.KLAGE_VURDERT_AV IS 'Hvem kalgen er vurdert av';
COMMENT ON COLUMN KLAGE_VURDERING_RESULTAT_DVH.KLAGEVURDERING IS 'klaagevurdering';
COMMENT ON COLUMN KLAGE_VURDERING_RESULTAT_DVH.KLAGE_AVVIST_AARSAK IS 'Årsak til at klagen ble avvist';
COMMENT ON COLUMN KLAGE_VURDERING_RESULTAT_DVH.KLAGE_MEDHOLD_AARSAK IS 'Årsak til medhold';
COMMENT ON COLUMN KLAGE_VURDERING_RESULTAT_DVH.KLAGE_VURDERING_OMGJOER IS 'Type omgjøring av klagen';
COMMENT ON COLUMN KLAGE_VURDERING_RESULTAT_DVH.VEDTAKSDATO_PAKLAGD_BEHANDLING IS 'Vedtaksdato på påklaget behandling';
COMMENT ON COLUMN KLAGE_VURDERING_RESULTAT_DVH.OPPRETTET_TID IS 'Opprettettidspunkt.';
COMMENT ON COLUMN KLAGE_VURDERING_RESULTAT_DVH.TRANS_TID IS 'Timestamp som forteller nå transaksjonen inntraff.';
COMMENT ON COLUMN KLAGE_VURDERING_RESULTAT_DVH.FUNKSJONELL_TID IS 'Et tidsstempel når transaksjonen er funksjonelt gyldig fra.';
COMMENT ON COLUMN KLAGE_VURDERING_RESULTAT_DVH.ENDRET_AV IS 'Opprettet_av eller endret_av i VL';
