ALTER TABLE GR_YTELSES_FORDELING add OPPGITT_DEKNINGSGRAD number(3);
ALTER TABLE GR_YTELSES_FORDELING add SAKSKOMPLEKS_DEKNINGSGRAD number(3);

COMMENT ON COLUMN GR_YTELSES_FORDELING.OPPGITT_DEKNINGSGRAD IS 'Dekningsgrad fra brukers søknad';
COMMENT ON COLUMN GR_YTELSES_FORDELING.SAKSKOMPLEKS_DEKNINGSGRAD IS 'Dekningsgrad for sakskompleks. Skal holdes i synk mellom begge parter.';
