DROP INDEX IDX_BEREGNING_1;

ALTER TABLE BR_LEGACY_ES_BEREGNING SET UNUSED (BEREGNING_RESULTAT_ID);

ALTER TABLE BEHANDLING_RESULTAT SET UNUSED (BEREGNING_RESULTAT_ID);

DROP TABLE BR_LEGACY_ES_BEREGNING_RES;

ALTER TABLE BR_LEGACY_ES_BEREGNING MODIFY BEHANDLING_ID NOT NULL;
