alter table YF_FORDELING_PERIODE ADD DOKUMENTASJON_VURDERING VARCHAR2(100 CHAR);
comment on column YF_FORDELING_PERIODE.DOKUMENTASJON_VURDERING IS 'Vurdering av dokumentasjon tilknyttet periode';

alter table UTTAK_RESULTAT_PERIODE_SOKNAD ADD DOKUMENTASJON_VURDERING VARCHAR2(100 CHAR);
comment on column UTTAK_RESULTAT_PERIODE_SOKNAD.DOKUMENTASJON_VURDERING IS 'Vurdering av dokumentasjon tilknyttet periode';
