alter table BEHANDLING_RESULTAT set unused (ENDRET_DEKNINGSGRAD, ENDRET_STOENADSKONTO);
alter table FAGSAK_RELASJON set unused (OVERSTYRT_DEKNINGSGRAD);
alter table SO_ANNEN_PART set unused (ARSAK, BEGRUNNELSE);
alter table VILKAR_RESULTAT set unused (OVERSTYRT, VILKAR_RESULTAT);
alter table YF_FORDELING_PERIODE set unused (VURDERING_TYPE);
alter table GR_YTELSES_FORDELING set unused (MIGRERT_DOK, OPPRINNELIGE_AKTKRAV_PER_ID, SAKSBEHANDLEDE_AKTKRAV_PER_ID, SO_DEKNINGSGRAD_ID, UTENOMSORG_ID, UTTAK_DOKUMENTASJON_ID);
