CREATE TABLE BEHANDLING_BREV_MELLOMLAGRING (
    ID NUMBER(19) NOT NULL
        CONSTRAINT PK_BREV_MELLOMLAGRING PRIMARY KEY,
    BEHANDLING_DOKUMENT_ID NUMBER(19) NOT NULL
        CONSTRAINT FK_BREV_MELLOMLAGR_BEH_DOK REFERENCES BEHANDLING_DOKUMENT,
    DOKUMENT_MAL_TYPE VARCHAR2(7 CHAR) NOT NULL,
    FRITEKST_HTML CLOB,
    OPPRETTET_AV VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
    OPPRETTET_TID TIMESTAMP(6) DEFAULT systimestamp NOT NULL,
    ENDRET_AV VARCHAR2(20 CHAR),
    ENDRET_TID TIMESTAMP(6)
);

CREATE SEQUENCE SEQ_BREV_MELLOMLAGRING
    MINVALUE 1000000
    INCREMENT BY 50
    NOCACHE;

CREATE UNIQUE INDEX UIDX_BREV_MELLOMLAGR_1
    ON BEHANDLING_BREV_MELLOMLAGRING (BEHANDLING_DOKUMENT_ID, DOKUMENT_MAL_TYPE);

CREATE INDEX IDX_BREV_MELLOMLAGR_DOK
    ON BEHANDLING_BREV_MELLOMLAGRING (BEHANDLING_DOKUMENT_ID);

COMMENT ON TABLE BEHANDLING_BREV_MELLOMLAGRING IS 'Mellomlagring av redigert brev-HTML per brevtype per behandling';
COMMENT ON COLUMN BEHANDLING_BREV_MELLOMLAGRING.BEHANDLING_DOKUMENT_ID IS 'FK til BEHANDLING_DOKUMENT';
COMMENT ON COLUMN BEHANDLING_BREV_MELLOMLAGRING.DOKUMENT_MAL_TYPE IS 'Brevmaltype (kode fra DokumentMalType)';
COMMENT ON COLUMN BEHANDLING_BREV_MELLOMLAGRING.FRITEKST_HTML IS 'Redigert HTML-innhold av brevet';
