ALTER TABLE YF_FORDELING_PERIODE add MORS_STILLINGSPROSENT NUMBER(5,2);
COMMENT ON COLUMN YF_FORDELING_PERIODE.MORS_STILLINGSPROSENT IS 'Avklart stillingsprosent for mor';

ALTER TABLE UTTAK_RESULTAT_PERIODE_SOKNAD add MORS_STILLINGSPROSENT NUMBER(5,2);
COMMENT ON COLUMN UTTAK_RESULTAT_PERIODE_SOKNAD.MORS_STILLINGSPROSENT IS 'Avklart stillingsprosent for mor';
