alter table FAGSAK_RELASJON modify (DEKNINGSGRAD null);

ALTER TABLE BR_FERIEPENGER_PR_AAR SET UNUSED (BEREGNINGSRESULTAT_ANDEL_ID);
ALTER TABLE BR_FERIEPENGER SET UNUSED (BEREGNINGSRESULTAT_FP_ID);


ALTER TABLE VILKAR ADD REGEL_VERSJON VARCHAR2(100 CHAR);
ALTER TABLE STOENADSKONTOBEREGNING ADD REGEL_VERSJON VARCHAR2(100 CHAR);
ALTER TABLE BR_BEREGNINGSRESULTAT ADD REGEL_VERSJON VARCHAR2(100 CHAR);
ALTER TABLE BR_FERIEPENGER ADD REGEL_VERSJON VARCHAR2(100 CHAR);
ALTER TABLE UTTAK_RESULTAT_DOK_REGEL ADD REGEL_VERSJON VARCHAR2(100 CHAR);
ALTER TABLE SVP_UTTAK_PERIODE ADD REGEL_VERSJON VARCHAR2(100 CHAR);
ALTER TABLE BG_PERIODE_REGEL_SPORING ADD REGEL_VERSJON VARCHAR2(100 CHAR);
ALTER TABLE BG_REGEL_SPORING ADD REGEL_VERSJON VARCHAR2(100 CHAR);

comment on column VILKAR.REGEL_VERSJON is 'Versjon av inngangsvilkårreglene som er brukt';
comment on column STOENADSKONTOBEREGNING.REGEL_VERSJON is 'Versjon av stønadskontoreglene som er brukt';
comment on column BR_BEREGNINGSRESULTAT.REGEL_VERSJON is 'Versjon av ytelsesberegningsreglene som er brukt';
comment on column BR_FERIEPENGER.REGEL_VERSJON is 'Versjon av feriepengereglene som er brukt';
comment on column UTTAK_RESULTAT_DOK_REGEL.REGEL_VERSJON is 'Versjon av foreldrepenger-uttaksreglene som er brukt';
comment on column SVP_UTTAK_PERIODE.REGEL_VERSJON is 'Versjon av svangerskapspenger-uttaksreglene som er brukt';
comment on column BG_PERIODE_REGEL_SPORING.REGEL_VERSJON is 'Versjon av beregningsreglene som er brukt';
comment on column BG_REGEL_SPORING.REGEL_VERSJON is 'Versjon av beregningsreglene som er brukt';

ALTER TABLE LAGRET_VEDTAK ADD FPSAK_VERSJON VARCHAR2(100 CHAR);
comment on column LAGRET_VEDTAK.FPSAK_VERSJON is 'Versjon av fpsak da vedtak ble fattet';
