CREATE TABLE BEHANDLING_MELLOMLAGRING (
    ID NUMBER(19) NOT NULL
        CONSTRAINT PK_MELLOMLAGRING PRIMARY KEY,
    BEHANDLING_ID NUMBER(19) NOT NULL
        CONSTRAINT FK_MELLOMLAGR_BEH REFERENCES BEHANDLING,
    TYPE VARCHAR2(30 CHAR) NOT NULL,
    INNHOLD CLOB NOT NULL,
    BESTILLING_LAAS CHAR(1) DEFAULT 'N' NOT NULL,
    VERSJON NUMBER(19) DEFAULT 0 NOT NULL,
    OPPRETTET_AV VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
    OPPRETTET_TID TIMESTAMP(6) DEFAULT systimestamp NOT NULL,
    ENDRET_AV VARCHAR2(20 CHAR),
    ENDRET_TID TIMESTAMP(6),
    CONSTRAINT CHK_UNIQUE_BEH_TYPE UNIQUE (BEHANDLING_ID, TYPE)
);

CREATE SEQUENCE SEQ_MELLOMLAGRING
    MINVALUE 1000000
    INCREMENT BY 50
    NOCACHE;

CREATE INDEX IDX_MELLOMLAGR_BEH
    ON BEHANDLING_MELLOMLAGRING (BEHANDLING_ID);

COMMENT ON TABLE BEHANDLING_MELLOMLAGRING IS 'Generell mellomlagring av innhold per type per behandling';
COMMENT ON COLUMN BEHANDLING_MELLOMLAGRING.BEHANDLING_ID IS 'FK til BEHANDLING';
COMMENT ON COLUMN BEHANDLING_MELLOMLAGRING.TYPE IS 'Type mellomlagring (f.eks. VARSEL_REVURDERING, INNHENT_OPPLYSNINGER, PAPIRSØKNAD)';
COMMENT ON COLUMN BEHANDLING_MELLOMLAGRING.INNHOLD IS 'Mellomlagret innhold (HTML, JSON, etc.)';
COMMENT ON COLUMN BEHANDLING_MELLOMLAGRING.BESTILLING_LAAS IS 'Lås som hindrer endring av mellomlagring mens brev-bestilling pågår (J/N)';
