update TILBAKEKREVING_VALG set videre_behandling = 'TILBAKEKR_OPPRETT' where VIDERE_BEHANDLING = 'TILBAKEKR_INFOTRYGD';
update HISTORIKKINNSLAG_FELT set FRA_VERDI_KODE = 'TILBAKEKR_OPPRETT' where FRA_VERDI_KODE = 'TILBAKEKR_INFOTRYGD';
update HISTORIKKINNSLAG_FELT set TIL_VERDI_KODE = 'TILBAKEKR_OPPRETT' where TIL_VERDI_KODE = 'TILBAKEKR_INFOTRYGD';
