ALTER TABLE UTTAK_RESULTAT add KONTO_BEREGNING_ID number(19) constraint FK_UTTAK_RESULTAT_4 references STOENADSKONTOBEREGNING;

COMMENT ON COLUMN UTTAK_RESULTAT.KONTO_BEREGNING_ID IS 'Stønadskontoutregning brukt i uttak';

create index IDX_UTTAK_RESULTAT_05 on UTTAK_RESULTAT (KONTO_BEREGNING_ID);
