CREATE TABLE FPOVERSIKT_FAGSAK_MIGRERING
(
    ID        NUMBER(19) NOT NULL,
    VERSJON   VARCHAR2(20 CHAR),
    FAGSAK_ID NUMBER(19) NOT NULL
        CONSTRAINT FK_FAGSAK
            REFERENCES FAGSAK
);
ALTER TABLE FPOVERSIKT_FAGSAK_MIGRERING  ADD CONSTRAINT PK_FPOVERSIKT_FAGSAK_MIGRERING PRIMARY KEY (ID);
CREATE SEQUENCE SEQ_FPOVERSIKT_FAGSAK_MIGRERING MINVALUE 1 START WITH 1 INCREMENT BY 10 NOCACHE NOCYCLE;

CREATE INDEX IDX_FPOVERSIKT_FAGSAK_MIGRERING_1 on FPOVERSIKT_FAGSAK_MIGRERING (FAGSAK_ID);

COMMENT ON TABLE FPOVERSIKT_FAGSAK_MIGRERING IS 'Tabell for å ha oversikt over hvilke saker som er migrert til fpoversikt.';
COMMENT ON COLUMN FPOVERSIKT_FAGSAK_MIGRERING.ID IS 'PK';
COMMENT ON COLUMN FPOVERSIKT_FAGSAK_MIGRERING.VERSJON IS 'versjon av migrering. Støtte for å kjøre flere ganger uten å måtte droppe innhold';
COMMENT ON COLUMN FPOVERSIKT_FAGSAK_MIGRERING.FAGSAK_ID IS 'fagsak';
