ALTER TABLE YF_FORDELING ADD OENSKER_JUSTERT_VED_FOEDSEL VARCHAR2(1 CHAR) DEFAULT 'N' ;
COMMENT ON COLUMN YF_FORDELING.OENSKER_JUSTERT_VED_FOEDSEL IS 'Oppgitt at bruker ønsker at fordelingen justeres ved fødsel';
