package no.nav.foreldrepenger.datavarehus.domene;

public enum VilkårIkkeOppfylt {
    MEDLEMSKAP,
    SØKNADSFRIST,
    OPPLYSNINGSPLIKT,
    SVANGERSKAPSPENGER,
    ENGANGSSTØNAD,
    FORELDREPENGER_GENERELL,
    FORELDREPENGER_OPPTJENING,
    FORELDREPENGER_BEREGNING,
    FORELDREPENGER_UTTAK
}
