package no.nav.foreldrepenger.datavarehus.domene;

public enum VilkårVerdiDvh {
    MEDLEMSKAP,
    SØKNADSFRIST,
    OPPLYSNINGSPLIKT,
    SVANGERSKAPSPENGER,
    ENGANSSTØNAD,
    FORELDREPENGER_GENERELL,
    FORELDREPENGER_OPPTJENING,
    FORELDREPENGER_BEREGNING,
    FORELDREPENGER_UTTAK
}
