package no.nav.foreldrepenger.inngangsvilkaar.medlemskap;

public enum MedlemskapAvvik {
    BOSATT_UTENLANDSOPPHOLD,
    BOSATT_MANGLENDE_BOSTEDSADRESSE,
    BOSATT_UTENLANDSADRESSE,
    BOSATT_UGYLDIG_PERSONSTATUS,
    TREDJELAND_MANGLENDE_LOVLIG_OPPHOLD,
    EØS_MANGLENDE_ANSETTELSE_MED_INNTEKT,
    MEDL_PERIODER,
}
