kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: fpsak
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  image:  {{image}}
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /fpsak/internal/health/isAlive
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  readiness:
    path: /fpsak/internal/health/isReady
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  prometheus:
    enabled: true
    path: /fpsak/internal/metrics/prometheus
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 80
  resources:
    limits:
      cpu: "4000m"
      memory: "3072Mi"
    requests:
      cpu: "200m"
      memory: "2688Mi"
  azure:
      application:
          enabled: true
          claims:
              extra:
                  - "NAVident"
                  - "azp_name"
  kafka:
      pool: {{kafkaPool}}
  accessPolicy:
      inbound:
          rules:
              - application: fp-frontend-azure
                cluster: dev-fss
              - application: fp-frontend-azure
                cluster: dev-gcp
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/defaultDSconfig
        kvPath: {{oracleconfig}}
      - mountPath: /var/run/secrets/nais.io/defaultDS
        kvPath:  {{oraclefpsaksecret}}
      - mountPath: /var/run/secrets/nais.io/dvhDS
        kvPath:  {{oracledvhsecret}}
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: {{fpsakserviceuser}}
      - mountPath: /var/run/secrets/nais.io/mq
        kvPath: {{mqserviceuser}}
      - mountPath: /var/run/secrets/nais.io/ldap
        kvPath: {{ldapserviceuser}}
      - mountPath: /var/run/secrets/nais.io/appdynamics
        kvPath: /apikey/appdynamics/{{environment}}
  env:
  {{#each env}}
   - name: {{@key}}
     value: "{{this}}"
  {{/each}}
