kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: fpsak
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  image:  {{image}}
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /fpsak/internal/health/isAlive
    initialDelay: 10
    periodSeconds: 10
    failureThreshold: 20
    timeout: 3
  readiness:
    path: /fpsak/internal/health/isReady
    initialDelay: 10
    periodSeconds: 10
    failureThreshold: 20
    timeout: 3
  preStopHook:
    http:
      path: /fpsak/internal/health/preStop
  prometheus:
    enabled: true
    path: /fpsak/internal/metrics/prometheus
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    scalingStrategy:
      cpu:
        thresholdPercentage: 80
  resources:
    limits:
      cpu: "{{limits.cpu}}"
      memory: "{{limits.mem}}"
    requests:
      cpu: "{{requests.cpu}}"
      memory: "{{requests.mem}}"
  kafka:
      pool: {{kafkaPool}}
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
        - id: "elastic-apm"
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/defaultDSconfig
        kvPath: {{oracleconfig}}
      - mountPath: /var/run/secrets/nais.io/defaultDS
        kvPath:  {{oraclefpsaksecret}}
      - mountPath: /var/run/secrets/nais.io/dvhDS
        kvPath:  {{oracledvhsecret}}
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: {{fpsakserviceuser}}
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
        groups:
          {{#each groups as |group|}}
            - id: "{{group}}"
          {{/each}}
  {{#if AZURE_IAC_RULES}}
  accessPolicy:
    inbound:
      rules:
      - application: statuspoll
        namespace: navdig
      {{#each AZURE_IAC_RULES}}
      - application: {{app}}
        namespace: {{namespace}}
        cluster: {{cluster}}
        {{#if scopes}}
        permissions:
          scopes:
          {{#each scopes}}
            - "{{this}}"
          {{/each}}
       {{/if}}
     {{/each}}
  {{/if}}
