name: Bygg pull request

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'

env:
  TZ: "Europe/Oslo"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
        oracle:
            image: gvenzl/oracle-xe:18.4.0-slim
            env:
                ORACLE_RANDOM_PASSWORD: true
            volumes:
                - ${GITHUB_WORKSPACE}/lokal-utvikling/oracle-init:/docker-entrypoint-initdb.d/
            ports:
                - 1521:1521
            options: --health-cmd healthcheck.sh --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v3
      - run:  git fetch --prune --unshallow

      - name: Setup maven
        uses: whelk-io/maven-settings-xml-action@v20
        with:
            repositories: '[{ "id": "github", "name": "github", "url": "https://maven.pkg.github.com/${{ github.repository }}", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } }]'
            servers: '[{ "id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.READER_TOKEN }}" }]'
            output_file: settings.xml

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Set build version
        run: |
          echo "BUILD_VERSION=4.0.0-$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build
        run: |
          echo "Building $BUILD_VERSION"
          mvn verify -q -e -B -s settings.xml -Drevision=${BUILD_VERSION}
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: ${{ job.services.oracle.ports[1521] }}
