name: Bygger image for test

on:
  repository_dispatch:
    types: [fpsak-docker-image-for-test]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Brukes ukenummer i cache_key da pomene endrer seg alt for ofte.
      # Alternative key med cache fra forrige uke som blir lagret etterpå under CACHE_KEY.
      - name: Set cache key
        run: |
          echo "::set-env name=CACHE_KEY::$(expr $(date +%V) - 1 + 1)"
          echo "::set-env name=PREVIOUS_CACHE_KEY::$(expr $(date +%V) - 1)"
      - uses: actions/cache@v1.1.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ env.CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ env.PREVIOUS_CACHE_KEY }}
      - name: Bygg og push docker-image
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        run: |
          docker build --build-arg DOWNLOAD_SCRIPT=getmqclients-GA.sh --build-arg TOKEN_CARRIER="$GITHUB_PASSWORD" \
            --build-arg VERSION=${{ github.event.client_payload.version }}  --pull \
            --tag ${{ github.event.client_payload.image }}-test:${{ github.event.client_payload.version }} \
            --tag ${{ github.event.client_payload.image }}-test:latest .

          echo "$GITHUB_PASSWORD" | docker login --username "$GITHUB_USERNAME" --password-stdin https://docker.pkg.github.com
          docker push ${{ github.event.client_payload.image }}-test:latest
          docker push ${{ github.event.client_payload.image }}-test:${TAG}
