name: Slash command dispatch
on:
    issue_comment:
        types: [ created ]

jobs:
    dispatcher:
        runs-on: ubuntu-latest
        steps:
            - name: Generate token
              uses: navikt/github-app-token-generator@v1
              id: get-token
              with:
                  private-key: ${{ secrets.FP_PRIVATE_KEY }}
                  app-id: ${{ secrets.FP_APP_ID }}
            - name: Slash command dispatch
              uses: peter-evans/slash-command-dispatch@v3
              with:
                  token: ${{ steps.get-token.outputs.token }} # Må ha PAT
                  commands: promote # matcher repository dispatch med navent 'promote-command'
                  issue-type: issue
                  allow-edits: true
